export type Song = {
  id: string | number;
  title: string;
  artist: string;
  year: number;
  videoId: string;
  artwork: string;
  category?: 'bollywood' | 'bhojpuri';
};

export type Scene = {
  id: string;
  title: string;
  hindi: string;
  description: string;
  icon: string;
  tint: string;
  image: string;
  ambienceAudio: string;
  playlist: Song[];
};

export function isBhojpuriSong(song: Song): boolean {
  if (song.category === 'bhojpuri') return true;
  if (song.category === 'bollywood') return false;
  if (typeof song.id === 'number' && ((song.id >= 701 && song.id <= 800) || (song.id >= 361 && song.id <= 400) || (song.id >= 570 && song.id <= 600) || (song.id >= 681 && song.id <= 700))) {
    return true;
  }
  const artist = song.artist.toLowerCase();
  const title = song.title.toLowerCase();
  const keywords = [
    'bhojpuri', 'manoj tiwari', 'radhe shyam', 'kalpana', 'sharda sinha', 'pawan singh',
    'khesari', 'ritesh', 'awadhesh', 'gayatri rani', 'mohammed aziz', 'mistu bardhan',
    'rambriksh', 'kabita rani', 'sunil chhaila', 'shubha mishra', 'alka chandrakar',
    'mohan rathod', 'indu sonali', 'neelkamal', 'dinesh lal', 'nirahua', 'bahangiya',
    'chhati', 'chhath', 'sasural', 'piawa', 'balam', 'odhaniya', 'rinkiya', 'chhalakata'
  ];
  return keywords.some(k => artist.includes(k) || title.includes(k));
}

export function getInterleavedPlaylist(playlist: Song[]): Song[] {
  if (!playlist || playlist.length === 0) return [];
  
  const bollywood: Song[] = [];
  const bhojpuri: Song[] = [];
  
  playlist.forEach(s => {
    if (isBhojpuriSong(s)) {
      bhojpuri.push(s);
    } else {
      bollywood.push(s);
    }
  });

  if (bollywood.length === 0 || bhojpuri.length === 0) return playlist;

  const result: Song[] = [];
  let hIdx = 0;
  let bIdx = 0;
  const total = playlist.length;

  while (result.length < total) {
    // 2 Bollywood songs
    for (let i = 0; i < 2; i++) {
      if (hIdx < bollywood.length) {
        result.push(bollywood[hIdx++]);
      } else if (bIdx < bhojpuri.length) {
        result.push(bhojpuri[bIdx++]);
      }
    }
    // 1 Bhojpuri song
    if (bIdx < bhojpuri.length) {
      result.push(bhojpuri[bIdx++]);
    } else if (hIdx < bollywood.length) {
      result.push(bollywood[hIdx++]);
    }
  }

  return result;
}


export const scenes: Scene[] = [
  {
    id: "bus-ka-safar",
    title: 'Bus Ka Safar',
    hindi: 'बस का सफ़र',
    description: 'Patna se Nawada — woh purani journey',
    icon: '🚌',
    tint: 'ochre',
    image: '/images/travel.jpg',
    ambienceAudio: '',
    playlist: [      { id: 101, title: "Tu Cheez Badi Hai Mast Mast", artist: "Udit Narayan, Kavita Krishnamurthy", year: 1994, videoId: "ZFZMPjMbvtU", artwork: "/images/travel.jpg" },
      { id: 102, title: "Tip Tip Barsa Paani", artist: "Udit Narayan, Alka Yagnik", year: 1994, videoId: "9u-r5W4WVO4", artwork: "/images/travel.jpg" },
      { id: 103, title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik", year: 1996, videoId: "QKfGl39ZJWI", artwork: "/images/travel.jpg" },
      { id: 104, title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", year: 1996, videoId: "ixCnsZswdpU", artwork: "/images/travel.jpg" },
      { id: 105, title: "Kitna Pyaara Tujhe Rab Ne Banaya", artist: "Udit Narayan, Alka Yagnik", year: 1996, videoId: "tZqlD8VN9AE", artwork: "/images/travel.jpg" },
      { id: 106, title: "Tujhe Dekha To", artist: "Kumar Sanu, Lata Mangeshkar", year: 1995, videoId: "cNV5hLSa9H8", artwork: "/images/travel.jpg" },
      { id: 107, title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", year: 1995, videoId: "s1LozokQjIg", artwork: "/images/travel.jpg" },
      { id: 108, title: "Ho Gaya Hai Tujhko To Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan", year: 1995, videoId: "hw_HpTI_Wkw", artwork: "/images/travel.jpg" },
      { id: 109, title: "Yeh Kaali Kaali Aankhen", artist: "Kumar Sanu, Anu Malik", year: 1993, videoId: "-IhD0cSuaqc", artwork: "/images/travel.jpg" },
      { id: 110, title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", year: 1993, videoId: "PUO7_Gi6ipg", artwork: "/images/travel.jpg" },
      { id: 111, title: "Chura Ke Dil Mera", artist: "Kumar Sanu, Alka Yagnik", year: 1994, videoId: "Yqj1_V90KJo", artwork: "/images/travel.jpg" },
      { id: 112, title: "Neela Dupatta Peela Suit", artist: "Abhijeet, Alka Yagnik", year: 1997, videoId: "1f-Btadq0a0", artwork: "/images/travel.jpg" },
      { id: 113, title: "Mera Piya Ghar Aaya", artist: "Kavita Krishnamurthy", year: 1995, videoId: "xVViRaALOLM", artwork: "/images/travel.jpg" },
      { id: 114, title: "Ankhiyon Se Goli Maare", artist: "Sonu Nigam, Jaspinder Narula", year: 1998, videoId: "rY_0SOlmrdY", artwork: "/images/travel.jpg" },
      { id: 115, title: "O Lal Dupatte Wali", artist: "Kumar Sanu, Sudesh Bhosle", year: 1993, videoId: "iLZGsICQrkU", artwork: "/images/travel.jpg" },
      { id: 116, title: "Saat Samundar Paar", artist: "Sadhana Sargam", year: 1992, videoId: "V20QpcSB27Q", artwork: "/images/travel.jpg" },
      { id: 117, title: "Jumma Chumma De De", artist: "Sudesh Bhosle, Kavita Krishnamurthy", year: 1991, videoId: "5gTToFIZp-g", artwork: "/images/travel.jpg" },
      { id: 118, title: "Tu Pagal Premi Awara", artist: "Shabbir Kumar, Kavita Krishnamurthy", year: 1992, videoId: "vnGLNdeE2Ss", artwork: "/images/travel.jpg" },
      { id: 119, title: "Ole Ole", artist: "Abhijeet Bhattacharya", year: 1994, videoId: "hcCvSmjHwGY", artwork: "/images/travel.jpg" },
      { id: 120, title: "Main Toh Raste Se Ja Raha Tha", artist: "Kumar Sanu, Alka Yagnik", year: 1995, videoId: "ekPjEpWKk74", artwork: "/images/travel.jpg" },
      { id: 121, title: "Husn Hai Suhana", artist: "Abhijeet, Chandana Dixit", year: 1995, videoId: "EsXG4YET4zs", artwork: "/images/travel.jpg" },
      { id: 122, title: "What Is Mobile Number", artist: "Sonu Nigam, Alka Yagnik", year: 1999, videoId: "_QqOhN4VYfE", artwork: "/images/travel.jpg" },
      { id: 123, title: "Sona Kitna Sona Hai", artist: "Udit Narayan, Poornima", year: 1997, videoId: "I6qPySAJWJs", artwork: "/images/travel.jpg" },
      { id: 124, title: "Mera Dil Tera Deewana", artist: "Alka Yagnik", year: 1999, videoId: "7Tr5jy2qEtE", artwork: "/images/travel.jpg" },
      { id: 125, title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", year: 1998, videoId: "K-pX4qwtAxA", artwork: "/images/travel.jpg" },
      { id: 126, title: "Dil Se Re", artist: "A.R. Rahman", year: 1998, videoId: "U3hZW62-KGA", artwork: "/images/travel.jpg" },
      { id: 127, title: "Ae Ajnabi", artist: "Udit Narayan, Mahalaxmi Iyer", year: 1998, videoId: "gga4bIVcA-A", artwork: "/images/travel.jpg" },
      { id: 128, title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", year: 1995, videoId: "jBpRItrod-Q", artwork: "/images/travel.jpg" },
      { id: 129, title: "Kaho Naa Pyaar Hai", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "-LESbtPT8uw", artwork: "/images/travel.jpg" },
      { id: 130, title: "Pyaar Ki Kashti Mein", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "t_oh_NkPtn0", artwork: "/images/travel.jpg" },
      { id: 131, title: "Na Tum Jaano Na Hum", artist: "Lucky Ali", year: 2000, videoId: "eSxo4l-epv8", artwork: "/images/travel.jpg" },
      { id: 132, title: "Ek Pal Ka Jeena", artist: "Lucky Ali", year: 2000, videoId: "aGbPyM6lzBs", artwork: "/images/travel.jpg" },
      { id: 133, title: "Aankhon Mein Teri", artist: "KK", year: 2007, videoId: "XIM9reXaY-Q", artwork: "/images/travel.jpg" },
      { id: 134, title: "You Are My Soniya", artist: "Sonu Nigam, Alka Yagnik", year: 2001, videoId: "2qBWL5Fplu0", artwork: "/images/travel.jpg" },
      { id: 135, title: "Bole Chudiyan", artist: "Amit Kumar, Sonu Nigam, Alka Yagnik, Udit Narayan, Kavita Krishnamurthy", year: 2001, videoId: "IBvg3WeqP1U", artwork: "/images/travel.jpg" },
      { id: 136, title: "Say Shava Shava", artist: "Sudesh Bhonsle, Alka Yagnik, Sunidhi Chauhan", year: 2001, videoId: "ZTARlM0pCP4", artwork: "/images/travel.jpg" },
      { id: 137, title: "It's the Time to Disco", artist: "Shaan, Vasundhara Das, Loy Mendonsa", year: 2003, videoId: "M03GOY5eINg", artwork: "/images/travel.jpg" },
      { id: 138, title: "Pretty Woman", artist: "Shankar Mahadevan, Ravi 'Rags' Khote", year: 2003, videoId: "Gcne5Wt-Qfo", artwork: "/images/travel.jpg" },
      { id: 139, title: "Maahi Ve", artist: "Sadhana Sargam, Sujata Bhattacharya, Udit Narayan, Sonu Nigam, Shankar Mahadevan", year: 2003, videoId: "1BWdglekty0", artwork: "/images/travel.jpg" },
      { id: 140, title: "Kal Ho Naa Ho", artist: "Sonu Nigam", year: 2003, videoId: "g0eO74UmRBs", artwork: "/images/travel.jpg" },
      { id: 141, title: "Koi Kahe Kehta Rahe", artist: "Shankar Mahadevan, Shaan, KK", year: 2001, videoId: "ctJI7pCbxAo", artwork: "/images/travel.jpg" },
      { id: 142, title: "Jaane Kyun", artist: "Vishal Dadlani, Sunidhi Chauhan", year: 2008, videoId: "n0PoVxBMUyE", artwork: "/images/travel.jpg" },
      { id: 143, title: "Dus Bahane", artist: "Shaan, KK", year: 2005, videoId: "qE3DfF66DNA", artwork: "/images/travel.jpg" },
      { id: 144, title: "Dhoom Machale", artist: "Sunidhi Chauhan", year: 2004, videoId: "2uUmHTgT65I", artwork: "/images/travel.jpg" },
      { id: 145, title: "Dil Laga Na", artist: "Sukhwinder Singh, Mahalakshmi Iyer", year: 2006, videoId: "gavPKwaMFyc", artwork: "/images/travel.jpg" },
      { id: 146, title: "Crazy Kiya Re", artist: "Sunidhi Chauhan", year: 2006, videoId: "J2Bh68GTUOU", artwork: "/images/travel.jpg" },
      { id: 147, title: "Aankh Marey", artist: "Kumar Sanu, Kavita Krishnamurthy", year: 1996, videoId: "2YDZDHF20_M", artwork: "/images/travel.jpg" },
      { id: 148, title: "Aaja Mahiya", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "VUJHo_p-CXM", artwork: "/images/travel.jpg" },
      { id: 149, title: "Humko Humise Chura Lo", artist: "Lata Mangeshkar, Udit Narayan", year: 2000, videoId: "zWPsjhBaRb0", artwork: "/images/travel.jpg" },
      { id: 150, title: "Soni Soni", artist: "Udit Narayan, Jaspinder Narula, Udbhav", year: 2000, videoId: "OpLD97fG9Hw", artwork: "/images/travel.jpg" },
      { id: 151, title: "Chalte Chalte", artist: "Udhbhav, Manohar Shetty, Ishaan", year: 2000, videoId: "kzTWRX9Dhrg", artwork: "/images/travel.jpg" },
      { id: 152, title: "Tumse Milna", artist: "Udit Narayan, Alka Yagnik", year: 2003, videoId: "3Y9zjI9oWaY", artwork: "/images/travel.jpg" },
      { id: 153, title: "Tere Naam", artist: "Udit Narayan, Alka Yagnik", year: 2003, videoId: "tDCZLB5A-nc", artwork: "/images/travel.jpg" },
      { id: 154, title: "Lagan Lagi", artist: "Sukhwinder Singh", year: 2003, videoId: "Ia1vUWaoqzE", artwork: "/images/travel.jpg" },
      { id: 155, title: "Aisa Kyun Hota Hai", artist: "Alka Yagnik", year: 2003, videoId: "ZuhBVz7z3SY", artwork: "/images/travel.jpg" },
      { id: 156, title: "Mujhe Neend Na Aaye", artist: "Udit Narayan, Anuradha Paudwal", year: 1990, videoId: "qjLPZsfA9Os", artwork: "/images/travel.jpg" },
      { id: 157, title: "Humko Sirf Tumse Pyaar Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1995, videoId: "t8aOUxUpoeI", artwork: "/images/travel.jpg" },
      { id: 158, title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", year: 1992, videoId: "SBfPs-PMGTA", artwork: "/images/travel.jpg" },
      { id: 159, title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", year: 1997, videoId: "yyquOeoB3gs", artwork: "/images/travel.jpg" },
      { id: 160, title: "Meri Duniya Tu Hi Re", artist: "Sonu Nigam, Shaan", year: 2007, videoId: "wsS1vWI7UGQ", artwork: "/images/travel.jpg" },
      { id: 161, title: "Rinkiya Ke Papa", artist: "Manoj Tiwari", year: 2000, videoId: "2Mv8UOiyTq0", artwork: "/images/travel.jpg" },
      { id: 162, title: "Goriya Chand Ke Anjoriya", artist: "Bhojpuri Folk", year: 2005, videoId: "VOtS75Xlfgg", artwork: "/images/travel.jpg" },
      { id: 163, title: "Kach Kach Baans Ke Bahangiya", artist: "Bhojpuri Folk", year: 2008, videoId: "Wne6-q9EvdU", artwork: "/images/travel.jpg" },
      { id: 164, title: "Lalki Odhaniya", artist: "Manoj Tiwari", year: 2004, videoId: "2Q5EQinkh1c", artwork: "/images/travel.jpg" },
      { id: 165, title: "Ae Raja Tani Ja Na Bahariya", artist: "Pawan Singh", year: 2018, videoId: "Ar2nHTWunbo", artwork: "/images/travel.jpg" },
      { id: 166, title: "Gori Tohar Kamar Lachkauwa", artist: "Ritesh Pandey", year: 2019, videoId: "mk_ftgCjZEg", artwork: "/images/travel.jpg" },
      { id: 167, title: "Kashi Hile Patna Hile", artist: "Manoj Tiwari", year: 2002, videoId: "orVDnK0MyMo", artwork: "/images/travel.jpg" },
      { id: 168, title: "Ganga Maiya Tohe Piyari Chadhaibo", artist: "Classic", year: 1963, videoId: "CPOp1s5RTAg", artwork: "/images/travel.jpg" },
      { id: 169, title: "Chhalakata Hamro Jawaniya", artist: "Pawan Singh, Kajal Raghwani", year: 2016, videoId: "c4JD7rEtIj8", artwork: "/images/travel.jpg" },
      { id: 170, title: "Kashi Hilela Patna Hilela", artist: "Bhojpuri Folk", year: 2005, videoId: "orVDnK0MyMo", artwork: "/images/travel.jpg" },
      { id: 171, title: "Saiyan Hamar", artist: "Bhojpuri Hit", year: 2010, videoId: "m40yAS42WVw", artwork: "/images/travel.jpg" },
      { id: 172, title: "Laiki Na Hoi", artist: "Bhojpuri Hit", year: 2015, videoId: "X3A_LG76Jz0", artwork: "/images/travel.jpg" },
      { id: 173, title: "Piya Pardesi", artist: "Bhojpuri Hit", year: 2012, videoId: "Ackl9qhE-LA", artwork: "/images/travel.jpg" },
      { id: 174, title: "Tohar Kajra Lagal Naina Mein", artist: "Bhojpuri Hit", year: 2011, videoId: "j5Tt0eyhaU8", artwork: "/images/travel.jpg" },
      { id: 175, title: "Humke Maaf Kari", artist: "Bhojpuri Hit", year: 2014, videoId: "iS2iEyLN79w", artwork: "/images/travel.jpg" },
      { id: 176, title: "Lal Chunariya Wali", artist: "Bhojpuri Hit", year: 2016, videoId: "h9qjGxeVnSA", artwork: "/images/travel.jpg" },
      { id: 177, title: "Goriya Chali Jaibu", artist: "Bhojpuri Hit", year: 2013, videoId: "EStG4Y7S_-E", artwork: "/images/travel.jpg" },
      { id: 178, title: "Aisan Na Dekha", artist: "Bhojpuri Hit", year: 2017, videoId: "3jOdRgOEIYg", artwork: "/images/travel.jpg" },
      { id: 179, title: "Balamua Ke Gaon Mein", artist: "Bhojpuri Hit", year: 2012, videoId: "VR475lvGG0U", artwork: "/images/travel.jpg" },
      { id: 180, title: "Sainya Ke Sath", artist: "Bhojpuri Hit", year: 2015, videoId: "RwsvEVNAm88", artwork: "/images/travel.jpg" },
      { id: 181, title: "Chadhal Jawani Rasgulla", artist: "Khesari Lal Yadav", year: 2018, videoId: "oJOKRI3ThwA", artwork: "/images/travel.jpg" },
      { id: 182, title: "Piyawa Se Pahile Hamaar Rahlu", artist: "Ritesh Pandey", year: 2017, videoId: "vwMR0yf4q04", artwork: "/images/travel.jpg" },
      { id: 183, title: "Tohar Dupatta", artist: "Bhojpuri Hit", year: 2019, videoId: "uiJr0Su-FCk", artwork: "/images/travel.jpg" },
      { id: 184, title: "Ae Ho More Raja", artist: "Bhojpuri Hit", year: 2016, videoId: "lzsACJsfhkY", artwork: "/images/travel.jpg" },
      { id: 185, title: "Sadiya Kare Da", artist: "Bhojpuri Hit", year: 2018, videoId: "qLcx_GnpUy4", artwork: "/images/travel.jpg" },
      { id: 186, title: "Kareja Mein Samail Badu Ho", artist: "Pawan Singh", year: 2015, videoId: "0gaQNhBu4Gc", artwork: "/images/travel.jpg" },
      { id: 187, title: "Lollypop Lagelu", artist: "Pawan Singh", year: 2008, videoId: "Gr8G_ldltDE", artwork: "/images/travel.jpg" },
      { id: 188, title: "Chhalakata Hamro Jawaniya 2", artist: "Pawan Singh", year: 2016, videoId: "c4JD7rEtIj8", artwork: "/images/travel.jpg" },
      { id: 189, title: "Piyawa Se Pahile", artist: "Pawan Singh", year: 2017, videoId: "vwMR0yf4q04", artwork: "/images/travel.jpg" },
      { id: 190, title: "Kamariya Hila Rahi Hai", artist: "Pawan Singh, Lauren Gottlieb", year: 2020, videoId: "Viiv41E8zIg", artwork: "/images/travel.jpg" },
      { id: 191, title: "Maugi Mile Na", artist: "Bhojpuri Hit", year: 2019, videoId: "9fSTa7tT03w", artwork: "/images/travel.jpg" },
      { id: 192, title: "Aara Hile Chapra Hile", artist: "Khesari Lal Yadav", year: 2019, videoId: "R3ekl0G3zKw", artwork: "/images/travel.jpg" },
      { id: 193, title: "Bagalwali Jaan Mareli", artist: "Manoj Tiwari", year: 2007, videoId: "cp0u9xHBZJ4", artwork: "/images/travel.jpg" },
      { id: 194, title: "Bhauji Ke Bahini", artist: "Bhojpuri Hit", year: 2016, videoId: "s_dH5xhrEZ8", artwork: "/images/travel.jpg" },
      { id: 195, title: "Gori Tohar Chunari Ba Lal Lal Re", artist: "Ritesh Pandey", year: 2019, videoId: "GiXO6ezMVas", artwork: "/images/travel.jpg" },
      { id: 196, title: "Tohar Gal Lagal Ba Gulabi", artist: "Bhojpuri Hit", year: 2018, videoId: "-Uvl0ripxVQ", artwork: "/images/travel.jpg" },
      { id: 197, title: "Nathuniya Pe Goli Mare", artist: "Neelkamal Singh", year: 2021, videoId: "KoK0c4_HDXw", artwork: "/images/travel.jpg" },
      { id: 198, title: "Saiyan Driver", artist: "Bhojpuri Hit", year: 2015, videoId: "g96Cp-nzRAw", artwork: "/images/travel.jpg" },
      { id: 199, title: "Raja Ho Raja", artist: "Bhojpuri Hit", year: 2014, videoId: "tnb7hSON80o", artwork: "/images/travel.jpg" },
      { id: 200, title: "Bhojpuriya Raja", artist: "Pawan Singh", year: 2016, videoId: "FF-_QBizdZQ", artwork: "/images/travel.jpg" }
    ]
  },
  {
    id: "desi-salon",
    title: 'Desi Salon',
    hindi: 'देसी सैलून',
    description: 'Radio, kainchi aur purani baatein',
    icon: '✂️',
    tint: 'rose',
    image: '/images/salon.jpg',
    ambienceAudio: '',
    playlist: [      { id: 201, title: "Mujhse Mohabbat Ka", artist: "Alka Yagnik, Kumar Sanu", year: 1993, videoId: "asVkFSVdJPo", artwork: "/images/salon.jpg" },
      { id: 202, title: "Dil Deta Hai Ro Ro Duhai", artist: "Pankaj Udhas", year: 1991, videoId: "M9JhDcAO50Y", artwork: "/images/salon.jpg" },
      { id: 203, title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", year: 1996, videoId: "ixCnsZswdpU", artwork: "/images/salon.jpg" },
      { id: 204, title: "Sona Kitna Sona Hai", artist: "Udit Narayan, Poornima", year: 1997, videoId: "I6qPySAJWJs", artwork: "/images/salon.jpg" },
      { id: 205, title: "Aapke Pyaar Mein Hum", artist: "Alka Yagnik", year: 2002, videoId: "FNpV3DQWUf8", artwork: "/images/salon.jpg" },
      { id: 206, title: "Aayiye Aapka Intezaar Tha", artist: "Kumar Sanu", year: 1994, videoId: "5PaXNmk5qIc", artwork: "/images/salon.jpg" },
      { id: 207, title: "Channe Ke Khet Mein", artist: "Poornima", year: 1994, videoId: "ti3-y50DsMk", artwork: "/images/salon.jpg" },
      { id: 208, title: "Tere Dar Par Sanam", artist: "Kumar Sanu", year: 1993, videoId: "05o4kCUY2Ys", artwork: "/images/salon.jpg" },
      { id: 209, title: "Jo Bhi Kasmein", artist: "Udit Narayan, Alka Yagnik", year: 2002, videoId: "B72_HsUR0Vc", artwork: "/images/salon.jpg" },
      { id: 210, title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik", year: 1996, videoId: "QKfGl39ZJWI", artwork: "/images/salon.jpg" },
      { id: 211, title: "Utha Le Jaoonga", artist: "Kumar Sanu, Anuradha Paudwal", year: 2002, videoId: "M0NsUnwY_9Y", artwork: "/images/salon.jpg" },
      { id: 212, title: "Tumse Milne Ko Dil", artist: "Kumar Sanu, Alka Yagnik", year: 1991, videoId: "5y_TCKNzAMI", artwork: "/images/salon.jpg" },
      { id: 213, title: "Chamma Chamma Baaje Re", artist: "Alka Yagnik", year: 1998, videoId: "1ZnPY1c3u_0", artwork: "/images/salon.jpg" },
      { id: 214, title: "College Ki Ladkiyon", artist: "Udit Narayan", year: 2002, videoId: "dU55dWKv8C4", artwork: "/images/salon.jpg" },
      { id: 215, title: "Aake Teri Baahon Mein", artist: "Lata Mangeshkar, S.P. Balasubrahmanyam", year: 1992, videoId: "98wwBzrFT-Q", artwork: "/images/salon.jpg" },
      { id: 216, title: "Kisi Din Banoongi Main", artist: "Alka Yagnik, Udit Narayan", year: 1995, videoId: "o2Fs6KqBNX8", artwork: "/images/salon.jpg" },
      { id: 217, title: "Ghoonghat Ki Aad Se", artist: "Alka Yagnik, Kumar Sanu", year: 1993, videoId: "cBw4H6Dx4vc", artwork: "/images/salon.jpg" },
      { id: 218, title: "Main Agar Saamne", artist: "Abhijeet, Alka Yagnik", year: 2002, videoId: "B2aHXbnu9dI", artwork: "/images/salon.jpg" },
      { id: 219, title: "Phoolon Sa Chehra Tera", artist: "Udit Narayan", year: 1993, videoId: "8fBzRDPH04k", artwork: "/images/salon.jpg" },
      { id: 220, title: "Phool Maangu Na Bahaar Maangu", artist: "Udit Narayan, Alka Yagnik", year: 1995, videoId: "_SiRjlYqlcE", artwork: "/images/salon.jpg" },
      { id: 221, title: "Tu Cheez Badi Hai Mast Mast", artist: "Udit Narayan, Kavita Krishnamurthy", year: 1994, videoId: "ZFZMPjMbvtU", artwork: "/images/salon.jpg" },
      { id: 222, title: "Tip Tip Barsa Paani", artist: "Udit Narayan, Alka Yagnik", year: 1994, videoId: "VMsn5-a45-s", artwork: "/images/salon.jpg" },
      { id: 223, title: "Yeh Kaali Kaali Aankhen", artist: "Kumar Sanu, Anu Malik", year: 1993, videoId: "-IhD0cSuaqc", artwork: "/images/salon.jpg" },
      { id: 224, title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", year: 1993, videoId: "PUO7_Gi6ipg", artwork: "/images/salon.jpg" },
      { id: 225, title: "Chura Ke Dil Mera", artist: "Kumar Sanu, Alka Yagnik", year: 1994, videoId: "Yqj1_V90KJo", artwork: "/images/salon.jpg" },
      { id: 226, title: "O Lal Dupatte Wali", artist: "Kumar Sanu, Sudesh Bhosle", year: 1993, videoId: "iLZGsICQrkU", artwork: "/images/salon.jpg" },
      { id: 227, title: "Saat Samundar Paar", artist: "Sadhana Sargam", year: 1992, videoId: "V20QpcSB27Q", artwork: "/images/salon.jpg" },
      { id: 228, title: "Jumma Chumma De De", artist: "Sudesh Bhosle, Kavita Krishnamurthy", year: 1991, videoId: "5gTToFIZp-g", artwork: "/images/salon.jpg" },
      { id: 229, title: "Ole Ole", artist: "Abhijeet", year: 1994, videoId: "hcCvSmjHwGY", artwork: "/images/salon.jpg" },
      { id: 230, title: "Main Toh Raste Se Ja Raha Tha", artist: "Kumar Sanu, Alka Yagnik", year: 1995, videoId: "I5_BhsgR9G8", artwork: "/images/salon.jpg" },
      { id: 231, title: "Husn Hai Suhana", artist: "Abhijeet, Chandana Dixit", year: 1995, videoId: "EsXG4YET4zs", artwork: "/images/salon.jpg" },
      { id: 232, title: "What Is Mobile Number", artist: "Sonu Nigam, Alka Yagnik", year: 1999, videoId: "_QqOhN4VYfE", artwork: "/images/salon.jpg" },
      { id: 233, title: "Mera Piya Ghar Aaya", artist: "Kavita Krishnamurthy", year: 1995, videoId: "xVViRaALOLM", artwork: "/images/salon.jpg" },
      { id: 234, title: "Ankhiyon Se Goli Maare", artist: "Sonu Nigam, Jaspinder Narula", year: 1998, videoId: "rY_0SOlmrdY", artwork: "/images/salon.jpg" },
      { id: 235, title: "Aankh Marey", artist: "Kumar Sanu, Kavita Krishnamurthy", year: 1996, videoId: "2YDZDHF20_M", artwork: "/images/salon.jpg" },
      { id: 236, title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", year: 1992, videoId: "SBfPs-PMGTA", artwork: "/images/salon.jpg" },
      { id: 237, title: "Tujhe Dekha To", artist: "Kumar Sanu, Lata Mangeshkar", year: 1995, videoId: "cNV5hLSa9H8", artwork: "/images/salon.jpg" },
      { id: 238, title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", year: 1995, videoId: "jBpRItrod-Q", artwork: "/images/salon.jpg" },
      { id: 239, title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", year: 1995, videoId: "s1LozokQjIg", artwork: "/images/salon.jpg" },
      { id: 240, title: "Ho Gaya Hai Tujhko To Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan", year: 1995, videoId: "hw_HpTI_Wkw", artwork: "/images/salon.jpg" },
      { id: 241, title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", year: 1997, videoId: "5SvIuD6wJRI", artwork: "/images/salon.jpg" },
      { id: 242, title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", year: 1998, videoId: "K-pX4qwtAxA", artwork: "/images/salon.jpg" },
      { id: 243, title: "Dil Se Re", artist: "A.R. Rahman", year: 1998, videoId: "U3hZW62-KGA", artwork: "/images/salon.jpg" },
      { id: 244, title: "Ae Ajnabi", artist: "Udit Narayan", year: 1998, videoId: "gga4bIVcA-A", artwork: "/images/salon.jpg" },
      { id: 245, title: "Kaho Naa Pyaar Hai", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "-LESbtPT8uw", artwork: "/images/salon.jpg" },
      { id: 246, title: "Ek Pal Ka Jeena", artist: "Lucky Ali", year: 2000, videoId: "aGbPyM6lzBs", artwork: "/images/salon.jpg" },
      { id: 247, title: "Na Tum Jaano Na Hum", artist: "Lucky Ali", year: 2000, videoId: "eSxo4l-epv8", artwork: "/images/salon.jpg" },
      { id: 248, title: "Pyaar Ki Kashti Mein", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "t_oh_NkPtn0", artwork: "/images/salon.jpg" },
      { id: 249, title: "Aaja Mahiya", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "I-m4cX22UlQ", artwork: "/images/salon.jpg" },
      { id: 250, title: "Humko Humise Chura Lo", artist: "Lata Mangeshkar, Udit Narayan", year: 2000, videoId: "zWPsjhBaRb0", artwork: "/images/salon.jpg" },
      { id: 251, title: "Soni Soni", artist: "Udit Narayan", year: 2000, videoId: "OpLD97fG9Hw", artwork: "/images/salon.jpg" },
      { id: 252, title: "Chalte Chalte", artist: "Udhbhav", year: 2000, videoId: "kzTWRX9Dhrg", artwork: "/images/salon.jpg" },
      { id: 253, title: "Koi Kahe Kehta Rahe", artist: "Shankar Mahadevan, Shaan, KK", year: 2001, videoId: "ctJI7pCbxAo", artwork: "/images/salon.jpg" },
      { id: 254, title: "You Are My Soniya", artist: "Sonu Nigam, Alka Yagnik", year: 2001, videoId: "2qBWL5Fplu0", artwork: "/images/salon.jpg" },
      { id: 255, title: "Bole Chudiyan", artist: "Amit Kumar, Sonu Nigam, Alka Yagnik", year: 2001, videoId: "IBvg3WeqP1U", artwork: "/images/salon.jpg" },
      { id: 256, title: "Maahi Ve", artist: "Sadhana Sargam, Sonu Nigam", year: 2003, videoId: "1BWdglekty0", artwork: "/images/salon.jpg" },
      { id: 257, title: "Pretty Woman", artist: "Shankar Mahadevan", year: 2003, videoId: "Gcne5Wt-Qfo", artwork: "/images/salon.jpg" },
      { id: 258, title: "It's the Time to Disco", artist: "Shaan, Vasundhara Das", year: 2003, videoId: "AYkXthbA12U", artwork: "/images/salon.jpg" },
      { id: 259, title: "Dhoom Machale", artist: "Sunidhi Chauhan", year: 2004, videoId: "2uUmHTgT65I", artwork: "/images/salon.jpg" },
      { id: 260, title: "Dus Bahane", artist: "Shaan, KK", year: 2005, videoId: "qE3DfF66DNA", artwork: "/images/salon.jpg" },
      { id: 261, title: "Rinkiya Ke Papa", artist: "Manoj Tiwari", year: 2000, videoId: "8jF5RmI2YNU", artwork: "/images/salon.jpg" },
      { id: 262, title: "Bagalwali Jaan Mareli", artist: "Manoj Tiwari", year: 2007, videoId: "cp0u9xHBZJ4", artwork: "/images/salon.jpg" },
      { id: 263, title: "Goriya Chand Ke Anjoriya", artist: "Manoj Tiwari", year: 2005, videoId: "VOtS75Xlfgg", artwork: "/images/salon.jpg" },
      { id: 264, title: "Chat Deni Maar Deli", artist: "Manoj Tiwari", year: 2008, videoId: "8jF5RmI2YNU", artwork: "/images/salon.jpg" },
      { id: 265, title: "Jab Se Chadhal Ba Jawani", artist: "Manoj Tiwari", year: 2006, videoId: "v3m3mphkLk0", artwork: "/images/salon.jpg" },
      { id: 266, title: "Ladki Hiy Heigh Bholtejwali", artist: "Manoj Tiwari", year: 2009, videoId: "L8N20UvaYzU", artwork: "/images/salon.jpg" },
      { id: 267, title: "Sasura Bada Paisawala", artist: "Manoj Tiwari", year: 2004, videoId: "M_GLtgCmyog", artwork: "/images/salon.jpg" },
      { id: 268, title: "Daroga Babu I Love You", artist: "Shreya Ghoshal", year: 2004, videoId: "juLFr5LRIus", artwork: "/images/salon.jpg" },
      { id: 269, title: "Damad Ji", artist: "Manoj Tiwari", year: 2005, videoId: "4KX4kYvI8h0", artwork: "/images/salon.jpg" },
      { id: 270, title: "Apna Bahini Se Byaah Kara Da", artist: "Manoj Tiwari", year: 2007, videoId: "wfGTlOa74EY", artwork: "/images/salon.jpg" },
      { id: 271, title: "Odhaniya Waali Se", artist: "Udit Narayan, Manoj Tiwari", year: 2006, videoId: "6Ro9YaG9bVg", artwork: "/images/salon.jpg" },
      { id: 272, title: "Dilwa Mangele Gamcha Bichayike", artist: "Kalpana Patowary", year: 2010, videoId: "NNublffAZWc", artwork: "/images/salon.jpg" },
      { id: 273, title: "Goriyan Chand Ke Anjoriya", artist: "Manoj Tiwari", year: 2005, videoId: "VOtS75Xlfgg", artwork: "/images/salon.jpg" },
      { id: 274, title: "Half Pantwali Se Labh Ho Gayil", artist: "Manoj Tiwari", year: 2008, videoId: "IcHRuEK1gJM", artwork: "/images/salon.jpg" },
      { id: 275, title: "Aiesan Dehalu Pappi", artist: "Manoj Tiwari", year: 2007, videoId: "sWa99nukCdI", artwork: "/images/salon.jpg" },
      { id: 276, title: "Ego Chhuma De Da Rajaji", artist: "Manoj Tiwari", year: 2006, videoId: "BODUu4SgRFs", artwork: "/images/salon.jpg" },
      { id: 277, title: "Pinjada Mein Fasi Gail Bulbul", artist: "Udit Narayan", year: 2005, videoId: "CAjrO6HBfM4", artwork: "/images/salon.jpg" },
      { id: 278, title: "Pyar Ke Har Baat Ho Gail", artist: "Udit Narayan", year: 2006, videoId: "A4CMyqaEKeM", artwork: "/images/salon.jpg" },
      { id: 279, title: "Driver Piyava Brake Mare Hachahach", artist: "Manoj Tiwari", year: 2009, videoId: "QxLvC5ueUlE", artwork: "/images/salon.jpg" },
      { id: 280, title: "Pyar Ke Pahila Sawan", artist: "Bhojpuri Classic", year: 2011, videoId: "dIhgEX7Xrhs", artwork: "/images/salon.jpg" },
      { id: 281, title: "Rasik Balma", artist: "Kalpana Patowary", year: 2012, videoId: "qUqFZsfhfrQ", artwork: "/images/salon.jpg" },
      { id: 282, title: "Ego Chumma Le La Raja Ji", artist: "Kalpana Patowary", year: 2011, videoId: "hhXvA2bXFsI", artwork: "/images/salon.jpg" },
      { id: 283, title: "Jekar Achake Me Dilwa Tut Gail", artist: "Kalpana Patowary", year: 2013, videoId: "3YJ9iPPFAsU", artwork: "/images/salon.jpg" },
      { id: 284, title: "Maroon Color Sadiya", artist: "Kalpana Patowary", year: 2024, videoId: "zmwfd8x0DrM", artwork: "/images/salon.jpg" },
      { id: 285, title: "Chumay La Ho", artist: "Kalpana Patowary", year: 2015, videoId: "-a5tl0aIAIg", artwork: "/images/salon.jpg" },
      { id: 286, title: "Maarela Kachaakach", artist: "Radhe Shyam Rasiya", year: 2014, videoId: "xI7m2wtOLL4", artwork: "/images/salon.jpg" },
      { id: 287, title: "Rahi Baithal Kera Ke Tham Pa", artist: "Awadhesh Premi Yadav", year: 2018, videoId: "KFuzItVTEG8", artwork: "/images/salon.jpg" },
      { id: 288, title: "Laal Chunariya Wali", artist: "Vinay Anand", year: 2016, videoId: "hH38X-nTNAg", artwork: "/images/salon.jpg" },
      { id: 289, title: "Saat Saheliyan", artist: "Dinesh Lal Yadav", year: 2010, videoId: "OaZUbUMX0nk", artwork: "/images/salon.jpg" },
      { id: 290, title: "Tu Hi Mor Balma", artist: "Bhojpuri Classic", year: 2008, videoId: "L6po6yipP60", artwork: "/images/salon.jpg" },
      { id: 291, title: "Gath Bandhan Pyar Ke", artist: "Pawan Singh", year: 2015, videoId: "V0F7v8fqMr8", artwork: "/images/salon.jpg" },
      { id: 292, title: "Sajanwa Tohre Khatir", artist: "Bhojpuri Classic", year: 2017, videoId: "FdLvVj7lva4", artwork: "/images/salon.jpg" },
      { id: 293, title: "Akhiya Ladiye Gayi", artist: "Bhojpuri Classic", year: 2016, videoId: "l7w8k5a_tSQ", artwork: "/images/salon.jpg" },
      { id: 294, title: "Uga Ho Suraj Dev", artist: "Bhojpuri Devotional", year: 2005, videoId: "6e6Hp6R5SVU", artwork: "/images/salon.jpg" },
      { id: 295, title: "Pinjrewali Muniya", artist: "Bhojpuri Classic", year: 2007, videoId: "IWoFIOA6RwI", artwork: "/images/salon.jpg" },
      { id: 296, title: "Hum Bahubali", artist: "Bhojpuri Classic", year: 2018, videoId: "xZIhU3x-KYc", artwork: "/images/salon.jpg" },
      { id: 297, title: "Saiya Driver Biwi Khalashi", artist: "Bhojpuri Classic", year: 2014, videoId: "FvpLxDBcY7I", artwork: "/images/salon.jpg" },
      { id: 298, title: "Naihar Ke Maro Piya Ke Chunari", artist: "Manoj Tiwari", year: 2008, videoId: "WyOiK392A-8", artwork: "/images/salon.jpg" },
      { id: 299, title: "Hamka Maafi Deido", artist: "Manoj Tiwari", year: 2006, videoId: "2OvOCqKe-w4", artwork: "/images/salon.jpg" },
      { id: 300, title: "Bandhan Tute Na", artist: "Manoj Tiwari", year: 2005, videoId: "vErS4FtQkWk", artwork: "/images/salon.jpg" }
    ]
  },
  {
    id: "chai-tapri",
    title: 'Chai Tapri',
    hindi: 'चाय की टपरी',
    description: 'Garam chai, baarish aur filmy gaane',
    icon: '☕',
    tint: 'brick',
    image: '/images/chai-tapri.jpg',
    ambienceAudio: '',
    playlist: [      { id: 301, title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", year: 1992, videoId: "SBfPs-PMGTA", artwork: "/images/chai-tapri.jpg" },
      { id: 302, title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", year: 1996, videoId: "ixCnsZswdpU", artwork: "/images/chai-tapri.jpg" },
      { id: 303, title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik", year: 1996, videoId: "QKfGl39ZJWI", artwork: "/images/chai-tapri.jpg" },
      { id: 304, title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", year: 1997, videoId: "5SvIuD6wJRI", artwork: "/images/chai-tapri.jpg" },
      { id: 305, title: "Tujhe Dekha To", artist: "Kumar Sanu, Lata Mangeshkar", year: 1995, videoId: "cNV5hLSa9H8", artwork: "/images/chai-tapri.jpg" },
      { id: 306, title: "Ho Gaya Hai Tujhko To Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan", year: 1995, videoId: "hw_HpTI_Wkw", artwork: "/images/chai-tapri.jpg" },
      { id: 307, title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", year: 1995, videoId: "jBpRItrod-Q", artwork: "/images/chai-tapri.jpg" },
      { id: 308, title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", year: 1995, videoId: "s1LozokQjIg", artwork: "/images/chai-tapri.jpg" },
      { id: 309, title: "Ek Ladki Ko Dekha", artist: "Kumar Sanu", year: 1994, videoId: "fTauOK8J-U8", artwork: "/images/chai-tapri.jpg" },
      { id: 310, title: "Kuch Na Kaho", artist: "Kumar Sanu", year: 1994, videoId: "I2NKqUvAwpE", artwork: "/images/chai-tapri.jpg" },
      { id: 311, title: "Tumse Milne Ki Tamanna Hai", artist: "SP Balasubrahmanyam", year: 1991, videoId: "Q5A0Yc2ZDB8", artwork: "/images/chai-tapri.jpg" },
      { id: 312, title: "Bahut Pyar Karte Hain", artist: "SP Balasubrahmanyam, Anuradha Paudwal", year: 1991, videoId: "2l5gDrfBQ_A", artwork: "/images/chai-tapri.jpg" },
      { id: 313, title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1991, videoId: "RVQsBlI35vw", artwork: "/images/chai-tapri.jpg" },
      { id: 314, title: "Jeeye To Jeeye Kaise", artist: "Kumar Sanu, SP Balasubrahmanyam, Pankaj Udhas", year: 1991, videoId: "XOxz0Hr3Hzo", artwork: "/images/chai-tapri.jpg" },
      { id: 315, title: "Dheere Dheere Se Meri Zindagi Mein Aana", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "KeyfUuXPOcY", artwork: "/images/chai-tapri.jpg" },
      { id: 316, title: "Nazar Ke Samne", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "HRX9DAxAjv0", artwork: "/images/chai-tapri.jpg" },
      { id: 317, title: "Bas Ek Sanam Chahiye", artist: "Kumar Sanu", year: 1990, videoId: "fBylcT-TWZw", artwork: "/images/chai-tapri.jpg" },
      { id: 318, title: "Tu Meri Zindagi Hai", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "yxCJOJORwlA", artwork: "/images/chai-tapri.jpg" },
      { id: 319, title: "Mujhe Neend Na Aaye", artist: "Udit Narayan, Anuradha Paudwal", year: 1990, videoId: "qjLPZsfA9Os", artwork: "/images/chai-tapri.jpg" },
      { id: 320, title: "Hum Pyar Karne Wale", artist: "Udit Narayan, Anuradha Paudwal", year: 1990, videoId: "tmf4SC84j6A", artwork: "/images/chai-tapri.jpg" },
      { id: 321, title: "Kitna Haseen Chehra", artist: "Kumar Sanu", year: 1994, videoId: "NzZxyWr9OA4", artwork: "/images/chai-tapri.jpg" },
      { id: 322, title: "Aisi Deewangi", artist: "Alka Yagnik, Vinod Rathod", year: 1992, videoId: "iRycjp7XVMg", artwork: "/images/chai-tapri.jpg" },
      { id: 323, title: "Sochenge Tumhe Pyar", artist: "Kumar Sanu", year: 1992, videoId: "17LL_iqlHE8", artwork: "/images/chai-tapri.jpg" },
      { id: 324, title: "Kisi Se Tum Pyar Karo", artist: "Kumar Sanu, Alka Yagnik", year: 2003, videoId: "JOt45suga2s", artwork: "/images/chai-tapri.jpg" },
      { id: 325, title: "Chura Ke Dil Mera", artist: "Kumar Sanu, Alka Yagnik", year: 1994, videoId: "Yqj1_V90KJo", artwork: "/images/chai-tapri.jpg" },
      { id: 326, title: "Main Toh Raste Se Ja Raha Tha", artist: "Kumar Sanu, Alka Yagnik", year: 1995, videoId: "I5_BhsgR9G8", artwork: "/images/chai-tapri.jpg" },
      { id: 327, title: "Husn Hai Suhana", artist: "Abhijeet, Chandana Dixit", year: 1995, videoId: "EsXG4YET4zs", artwork: "/images/chai-tapri.jpg" },
      { id: 328, title: "Sona Kitna Sona Hai", artist: "Udit Narayan, Poornima", year: 1997, videoId: "I6qPySAJWJs", artwork: "/images/chai-tapri.jpg" },
      { id: 329, title: "Ankhiyon Se Goli Maare", artist: "Sonu Nigam, Jaspinder Narula", year: 1998, videoId: "rY_0SOlmrdY", artwork: "/images/chai-tapri.jpg" },
      { id: 330, title: "O Lal Dupatte Wali", artist: "Kumar Sanu, Sudesh Bhosle", year: 1993, videoId: "iLZGsICQrkU", artwork: "/images/chai-tapri.jpg" },
      { id: 331, title: "Tu Cheez Badi Hai Mast Mast", artist: "Udit Narayan, Kavita Krishnamurthy", year: 1994, videoId: "ZFZMPjMbvtU", artwork: "/images/chai-tapri.jpg" },
      { id: 332, title: "Tip Tip Barsa Paani", artist: "Udit Narayan, Alka Yagnik", year: 1994, videoId: "9u-r5W4WVO4", artwork: "/images/chai-tapri.jpg" },
      { id: 333, title: "Yeh Kaali Kaali Aankhen", artist: "Kumar Sanu, Anu Malik", year: 1993, videoId: "-IhD0cSuaqc", artwork: "/images/chai-tapri.jpg" },
      { id: 334, title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", year: 1993, videoId: "PUO7_Gi6ipg", artwork: "/images/chai-tapri.jpg" },
      { id: 335, title: "Saat Samundar Paar", artist: "Sadhana Sargam", year: 1992, videoId: "V20QpcSB27Q", artwork: "/images/chai-tapri.jpg" },
      { id: 336, title: "Ole Ole", artist: "Abhijeet", year: 1994, videoId: "hcCvSmjHwGY", artwork: "/images/chai-tapri.jpg" },
      { id: 337, title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", year: 1998, videoId: "K-pX4qwtAxA", artwork: "/images/chai-tapri.jpg" },
      { id: 338, title: "Ae Ajnabi", artist: "Udit Narayan", year: 1998, videoId: "gga4bIVcA-A", artwork: "/images/chai-tapri.jpg" },
      { id: 339, title: "Dil Se Re", artist: "A.R. Rahman", year: 1998, videoId: "U3hZW62-KGA", artwork: "/images/chai-tapri.jpg" },
      { id: 340, title: "Satrangi Re", artist: "Sonu Nigam, Kavita Krishnamurthy", year: 1998, videoId: "33cQdeFhNgU", artwork: "/images/chai-tapri.jpg" },
      { id: 341, title: "Kaho Naa Pyaar Hai", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "-LESbtPT8uw", artwork: "/images/chai-tapri.jpg" },
      { id: 342, title: "Na Tum Jaano Na Hum", artist: "Lucky Ali", year: 2000, videoId: "eSxo4l-epv8", artwork: "/images/chai-tapri.jpg" },
      { id: 343, title: "Ek Pal Ka Jeena", artist: "Lucky Ali", year: 2000, videoId: "aGbPyM6lzBs", artwork: "/images/chai-tapri.jpg" },
      { id: 344, title: "Aaja Mahiya", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "VUJHo_p-CXM", artwork: "/images/chai-tapri.jpg" },
      { id: 345, title: "Humko Humise Chura Lo", artist: "Lata Mangeshkar, Udit Narayan", year: 2000, videoId: "zWPsjhBaRb0", artwork: "/images/chai-tapri.jpg" },
      { id: 346, title: "Chalte Chalte", artist: "Udhbhav", year: 2000, videoId: "kzTWRX9Dhrg", artwork: "/images/chai-tapri.jpg" },
      { id: 347, title: "Soni Soni", artist: "Udit Narayan", year: 2000, videoId: "OpLD97fG9Hw", artwork: "/images/chai-tapri.jpg" },
      { id: 348, title: "Koi Kahe Kehta Rahe", artist: "Shankar Mahadevan, Shaan, KK", year: 2001, videoId: "ctJI7pCbxAo", artwork: "/images/chai-tapri.jpg" },
      { id: 349, title: "Jaane Kyun", artist: "Vishal Dadlani, Sunidhi Chauhan", year: 2001, videoId: "n0PoVxBMUyE", artwork: "/images/chai-tapri.jpg" },
      { id: 350, title: "Tanhayee", artist: "Sonu Nigam", year: 2001, videoId: "ZkwaiIGoyT4", artwork: "/images/chai-tapri.jpg" },
      { id: 351, title: "Kal Ho Naa Ho", artist: "Sonu Nigam", year: 2003, videoId: "g0eO74UmRBs", artwork: "/images/chai-tapri.jpg" },
      { id: 352, title: "Maahi Ve", artist: "Sadhana Sargam, Sonu Nigam", year: 2003, videoId: "1BWdglekty0", artwork: "/images/chai-tapri.jpg" },
      { id: 353, title: "Pretty Woman", artist: "Shankar Mahadevan", year: 2003, videoId: "Gcne5Wt-Qfo", artwork: "/images/chai-tapri.jpg" },
      { id: 354, title: "It's the Time to Disco", artist: "Shaan, Vasundhara Das", year: 2003, videoId: "M03GOY5eINg", artwork: "/images/chai-tapri.jpg" },
      { id: 355, title: "Tere Naam", artist: "Udit Narayan, Alka Yagnik", year: 2003, videoId: "tDCZLB5A-nc", artwork: "/images/chai-tapri.jpg" },
      { id: 356, title: "Tumse Milna", artist: "Udit Narayan, Alka Yagnik", year: 2003, videoId: "3Y9zjI9oWaY", artwork: "/images/chai-tapri.jpg" },
      { id: 357, title: "Lagan Lagi", artist: "Sukhwinder Singh", year: 2003, videoId: "Ia1vUWaoqzE", artwork: "/images/chai-tapri.jpg" },
      { id: 358, title: "Aankhon Mein Teri", artist: "KK", year: 2007, videoId: "XIM9reXaY-Q", artwork: "/images/chai-tapri.jpg" },
      { id: 359, title: "Dus Bahane", artist: "Shaan, KK", year: 2005, videoId: "qE3DfF66DNA", artwork: "/images/chai-tapri.jpg" },
      { id: 360, title: "Dhoom Machale", artist: "Sunidhi Chauhan", year: 2004, videoId: "2uUmHTgT65I", artwork: "/images/chai-tapri.jpg" },
      { id: 361, title: "Rinkiya Ke Papa", artist: "Manoj Tiwari", year: 2000, videoId: "8jF5RmI2YNU", artwork: "/images/chai-tapri.jpg" },
      { id: 362, title: "Bagalwali Jaan Mareli", artist: "Manoj Tiwari", year: 2007, videoId: "cp0u9xHBZJ4", artwork: "/images/chai-tapri.jpg" },
      { id: 363, title: "Goriya Chand Ke Anjoriya", artist: "Manoj Tiwari", year: 2005, videoId: "VOtS75Xlfgg", artwork: "/images/chai-tapri.jpg" },
      { id: 364, title: "Chat Deni Maar Deli", artist: "Manoj Tiwari", year: 2008, videoId: "8jF5RmI2YNU", artwork: "/images/chai-tapri.jpg" },
      { id: 365, title: "Lalki Odhaniya", artist: "Manoj Tiwari", year: 2004, videoId: "2Q5EQinkh1c", artwork: "/images/chai-tapri.jpg" },
      { id: 366, title: "Sasura Bada Paisawala", artist: "Manoj Tiwari", year: 2004, videoId: "M_GLtgCmyog", artwork: "/images/chai-tapri.jpg" },
      { id: 367, title: "Daroga Babu I Love You", artist: "Manoj Tiwari", year: 2004, videoId: "juLFr5LRIus", artwork: "/images/chai-tapri.jpg" },
      { id: 368, title: "Damad Ji", artist: "Manoj Tiwari", year: 2005, videoId: "4KX4kYvI8h0", artwork: "/images/chai-tapri.jpg" },
      { id: 369, title: "Odhaniya Wali Se", artist: "Manoj Tiwari", year: 2006, videoId: "fedVbU26Gv0", artwork: "/images/chai-tapri.jpg" },
      { id: 370, title: "Driver Piyawa Brake Mare", artist: "Manoj Tiwari", year: 2009, videoId: "J4S9Gw3zpoA", artwork: "/images/chai-tapri.jpg" },
      { id: 371, title: "Raja Ji Ke Dilwa", artist: "Bhojpuri Hit", year: 2012, videoId: "cQM55aOrZCg", artwork: "/images/chai-tapri.jpg" },
      { id: 372, title: "Chhalakata Hamro Jawaniya", artist: "Pawan Singh", year: 2016, videoId: "c4JD7rEtIj8", artwork: "/images/chai-tapri.jpg" },
      { id: 373, title: "Piyawa Se Pahile Hamaar Rahlu", artist: "Ritesh Pandey", year: 2017, videoId: "vwMR0yf4q04", artwork: "/images/chai-tapri.jpg" },
      { id: 374, title: "Gori Tohar Kamar Lachkauwa", artist: "Ritesh Pandey", year: 2019, videoId: "h4MEAaWZ7fY", artwork: "/images/chai-tapri.jpg" },
      { id: 375, title: "Ae Raja Tani Ja Na Bahariya", artist: "Pawan Singh", year: 2018, videoId: "3hg5N5hG1Cc", artwork: "/images/chai-tapri.jpg" },
      { id: 376, title: "Kashi Hile Patna Hile", artist: "Manoj Tiwari", year: 2002, videoId: "orVDnK0MyMo", artwork: "/images/chai-tapri.jpg" },
      { id: 377, title: "Aara Hile Chapra Hile", artist: "Khesari Lal Yadav", year: 2019, videoId: "zQqJmpCJZtc", artwork: "/images/chai-tapri.jpg" },
      { id: 378, title: "Laiki Na Hoi", artist: "Bhojpuri Hit", year: 2015, videoId: "sURiWAa7eFk", artwork: "/images/chai-tapri.jpg" },
      { id: 379, title: "Piya Pardesi", artist: "Bhojpuri Hit", year: 2012, videoId: "Ackl9qhE-LA", artwork: "/images/chai-tapri.jpg" },
      { id: 380, title: "Saiyan Hamar", artist: "Bhojpuri Hit", year: 2010, videoId: "m40yAS42WVw", artwork: "/images/chai-tapri.jpg" },
      { id: 381, title: "Tohar Kajra Lagal Naina Mein", artist: "Bhojpuri Hit", year: 2011, videoId: "j5Tt0eyhaU8", artwork: "/images/chai-tapri.jpg" },
      { id: 382, title: "Lal Chunariya Wali", artist: "Bhojpuri Hit", year: 2016, videoId: "h9qjGxeVnSA", artwork: "/images/chai-tapri.jpg" },
      { id: 383, title: "Goriya Chali Jaibu", artist: "Bhojpuri Hit", year: 2013, videoId: "EStG4Y7S_-E", artwork: "/images/chai-tapri.jpg" },
      { id: 384, title: "Tohar Dupatta", artist: "Bhojpuri Hit", year: 2019, videoId: "uiJr0Su-FCk", artwork: "/images/chai-tapri.jpg" },
      { id: 385, title: "Kareja Mein Samail Badu Ho", artist: "Pawan Singh", year: 2015, videoId: "PJx-Agxq2NM", artwork: "/images/chai-tapri.jpg" },
      { id: 386, title: "Chadhal Jawani Rasgulla", artist: "Khesari Lal Yadav", year: 2018, videoId: "oJOKRI3ThwA", artwork: "/images/chai-tapri.jpg" },
      { id: 387, title: "Maugi Mile Na", artist: "Bhojpuri Hit", year: 2019, videoId: "Q5uOjR3351o", artwork: "/images/chai-tapri.jpg" },
      { id: 388, title: "Bhauji Ke Bahini", artist: "Bhojpuri Hit", year: 2016, videoId: "nXABRgdme2c", artwork: "/images/chai-tapri.jpg" },
      { id: 389, title: "Ae Ho More Raja", artist: "Bhojpuri Hit", year: 2016, videoId: "cjaXzoCYnho", artwork: "/images/chai-tapri.jpg" },
      { id: 390, title: "Sadiya Kare Da", artist: "Bhojpuri Hit", year: 2018, videoId: "fgLhVyrg5d8", artwork: "/images/chai-tapri.jpg" },
      { id: 391, title: "Nathuniya Pe Goli Mare", artist: "Neelkamal Singh", year: 2021, videoId: "KoK0c4_HDXw", artwork: "/images/chai-tapri.jpg" },
      { id: 392, title: "Saiyan Driver", artist: "Bhojpuri Hit", year: 2015, videoId: "8QxOat8s8Oo", artwork: "/images/chai-tapri.jpg" },
      { id: 393, title: "Raja Ho Raja", artist: "Bhojpuri Hit", year: 2014, videoId: "tnb7hSON80o", artwork: "/images/chai-tapri.jpg" },
      { id: 394, title: "Bhojpuriya Raja", artist: "Pawan Singh", year: 2016, videoId: "FF-_QBizdZQ", artwork: "/images/chai-tapri.jpg" },
      { id: 395, title: "Kach Kach Baans Ke Bahangiya", artist: "Bhojpuri Folk", year: 2008, videoId: "OSQI61ilOsM", artwork: "/images/chai-tapri.jpg" },
      { id: 396, title: "Ganga Maiya Tohe Piyari Chadhaibo", artist: "Bhojpuri Classic", year: 1963, videoId: "CPOp1s5RTAg", artwork: "/images/chai-tapri.jpg" },
      { id: 397, title: "Ego Chhuma De Da Rajaji", artist: "Manoj Tiwari", year: 2006, videoId: "CsrPirKKYgA", artwork: "/images/chai-tapri.jpg" },
      { id: 398, title: "Dilwa Mangele Gamcha Bichayike", artist: "Kalpana Patowary", year: 2010, videoId: "NNublffAZWc", artwork: "/images/chai-tapri.jpg" },
      { id: 399, title: "Rasik Balma", artist: "Kalpana Patowary", year: 2012, videoId: "nqmeKe0rYT0", artwork: "/images/chai-tapri.jpg" },
      { id: 400, title: "Lollypop Lagelu", artist: "Pawan Singh", year: 2008, videoId: "Gr8G_ldltDE", artwork: "/images/chai-tapri.jpg" }
    ]
  },
  {
    id: "railway-station",
    title: 'Railway Station',
    hindi: 'रेलवे स्टेशन',
    description: 'Platform ki raunak aur ek lambi raat',
    icon: '🚂',
    tint: 'teal',
    image: '/images/railway.jpg',
    ambienceAudio: '',
    playlist: [      { id: 401, title: "Musafir Hoon Yaaron", artist: "Kishore Kumar", year: 1972, videoId: "1DwROkoAAcI", artwork: "/images/railway.jpg" },
      { id: 402, title: "Zindagi Ek Safar Hai Suhana", artist: "Kishore Kumar", year: 1971, videoId: "LlvoY4v5zm0", artwork: "/images/railway.jpg" },
      { id: 403, title: "Gaadi Bula Rahi Hai", artist: "Kishore Kumar", year: 1974, videoId: "njnCoN9Qlvw", artwork: "/images/railway.jpg" },
      { id: 404, title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", year: 1998, videoId: "K-pX4qwtAxA", artwork: "/images/railway.jpg" },
      { id: 405, title: "Aao Milo Chalo", artist: "Shaan, Ustad Sultan Khan", year: 2007, videoId: "Mo5tQDcs__g", artwork: "/images/railway.jpg" },
      { id: 406, title: "Safarnama", artist: "Lucky Ali", year: 2015, videoId: "7mTDBsdfw88", artwork: "/images/railway.jpg" },
      { id: 407, title: "Yun Hi Chala Chal", artist: "Udit Narayan, Hariharan", year: 2004, videoId: "JbNlkYQG5XI", artwork: "/images/railway.jpg" },
      { id: 408, title: "Ilahi", artist: "Arijit Singh", year: 2013, videoId: "bA7Yhb058W8", artwork: "/images/railway.jpg" },
      { id: 409, title: "Phir Se Ud Chala", artist: "Mohit Chauhan", year: 2011, videoId: "2mWaqsC3U7k", artwork: "/images/railway.jpg" },
      { id: 410, title: "Patakha Guddi", artist: "Nooran Sisters", year: 2014, videoId: "8HDTS80dlr4", artwork: "/images/railway.jpg" },
      { id: 411, title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik", year: 1996, videoId: "QKfGl39ZJWI", artwork: "/images/railway.jpg" },
      { id: 412, title: "Pardesi Jaane Wale", artist: "Udit Narayan, Anuradha Paudwal", year: 2000, videoId: "9fShneWE5vk", artwork: "/images/railway.jpg" },
      { id: 413, title: "Aa Ab Laut Chalen", artist: "Udit Narayan, Alka Yagnik", year: 1999, videoId: "mZE6OVdNhsk", artwork: "/images/railway.jpg" },
      { id: 414, title: "Chhod Aaye Hum", artist: "Hariharan, Suresh Wadkar, Vinod Sehgal", year: 1996, videoId: "RraeHart9uY", artwork: "/images/railway.jpg" },
      { id: 415, title: "Aye Mere Humsafar", artist: "Vinod Rathod, Alka Yagnik", year: 1993, videoId: "UCsW7nea7sI", artwork: "/images/railway.jpg" },
      { id: 416, title: "Tu Hi Re", artist: "Hariharan, Chithra", year: 1995, videoId: "BFnQbgazL3g", artwork: "/images/railway.jpg" },
      { id: 417, title: "Ae Ajnabi", artist: "Udit Narayan", year: 1998, videoId: "gga4bIVcA-A", artwork: "/images/railway.jpg" },
      { id: 418, title: "Dil Se Re", artist: "A.R. Rahman", year: 1998, videoId: "U3hZW62-KGA", artwork: "/images/railway.jpg" },
      { id: 419, title: "Satrangi Re", artist: "Sonu Nigam", year: 1998, videoId: "33cQdeFhNgU", artwork: "/images/railway.jpg" },
      { id: 420, title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", year: 1997, videoId: "5SvIuD6wJRI", artwork: "/images/railway.jpg" },
      { id: 421, title: "Kaho Naa Pyaar Hai", artist: "Udit Narayan, Alka Yagnik", year: 2000, videoId: "-LESbtPT8uw", artwork: "/images/railway.jpg" },
      { id: 422, title: "Na Tum Jaano Na Hum", artist: "Lucky Ali", year: 2000, videoId: "eSxo4l-epv8", artwork: "/images/railway.jpg" },
      { id: 423, title: "Ek Ladki Ko Dekha", artist: "Kumar Sanu", year: 1994, videoId: "fTauOK8J-U8", artwork: "/images/railway.jpg" },
      { id: 424, title: "Kuch Na Kaho", artist: "Kumar Sanu", year: 1994, videoId: "I2NKqUvAwpE", artwork: "/images/railway.jpg" },
      { id: 425, title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", year: 1992, videoId: "SBfPs-PMGTA", artwork: "/images/railway.jpg" },
      { id: 426, title: "Tujhe Dekha To", artist: "Kumar Sanu, Lata Mangeshkar", year: 1995, videoId: "cNV5hLSa9H8", artwork: "/images/railway.jpg" },
      { id: 427, title: "Ho Gaya Hai Tujhko To Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan", year: 1995, videoId: "hw_HpTI_Wkw", artwork: "/images/railway.jpg" },
      { id: 428, title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", year: 1995, videoId: "jBpRItrod-Q", artwork: "/images/railway.jpg" },
      { id: 429, title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", year: 1995, videoId: "s1LozokQjIg", artwork: "/images/railway.jpg" },
      { id: 430, title: "Yeh Kahan Aa Gaye Hum", artist: "Lata Mangeshkar, Amitabh Bachchan", year: 1981, videoId: "43wT0xhvfsA", artwork: "/images/railway.jpg" },
      { id: 431, title: "Aap Ki Aankhon Mein Kuch", artist: "Kishore Kumar, Lata Mangeshkar", year: 1978, videoId: "qn3WEdLtp-g", artwork: "/images/railway.jpg" },
      { id: 432, title: "Aapke Pyaar Mein Hum", artist: "Alka Yagnik", year: 2002, videoId: "FNpV3DQWUf8", artwork: "/images/railway.jpg" },
      { id: 433, title: "Aadat", artist: "Atif Aslam", year: 2005, videoId: "e5LShHAE03A", artwork: "/images/railway.jpg" },
      { id: 434, title: "Sach Keh Raha Hai Deewana", artist: "KK", year: 2001, videoId: "kp-Bqr1Gtyw", artwork: "/images/railway.jpg" },
      { id: 435, title: "Zara Zara", artist: "Bombay Jayashri", year: 2001, videoId: "sjij_VKa2QQ", artwork: "/images/railway.jpg" },
      { id: 436, title: "Tu Bin Bataye", artist: "Naresh Iyer, Madhushree", year: 2006, videoId: "UqblLzBwlns", artwork: "/images/railway.jpg" },
      { id: 437, title: "Roobaroo", artist: "A.R. Rahman, Naresh Iyer", year: 2006, videoId: "8kMv5ssr6Dw", artwork: "/images/railway.jpg" },
      { id: 438, title: "Khoon Chala", artist: "Mohit Chauhan", year: 2006, videoId: "OAV1-Rbs-Gs", artwork: "/images/railway.jpg" },
      { id: 439, title: "Luka Chuppi", artist: "Lata Mangeshkar, A.R. Rahman", year: 2006, videoId: "FFpgYjL2aJo", artwork: "/images/railway.jpg" },
      { id: 440, title: "Tere Liye", artist: "Lata Mangeshkar, Roop Kumar Rathod", year: 2004, videoId: "jo6iAkSoraY", artwork: "/images/railway.jpg" },
      { id: 441, title: "Main Yahan Tu Wahan", artist: "Amitabh Bachchan, Alka Yagnik", year: 2003, videoId: "himlbsMN4g8", artwork: "/images/railway.jpg" },
      { id: 442, title: "Do Pal", artist: "Lata Mangeshkar, Sonu Nigam", year: 2004, videoId: "HPsxxBhv9kc", artwork: "/images/railway.jpg" },
      { id: 443, title: "Hum To Bhai Jaise Hain", artist: "Lata Mangeshkar", year: 2004, videoId: "c_L5nSf91zs", artwork: "/images/railway.jpg" },
      { id: 444, title: "Aisa Des Hai Mera", artist: "Lata Mangeshkar, Udit Narayan", year: 2004, videoId: "wDheWYmNEhQ", artwork: "/images/railway.jpg" },
      { id: 445, title: "Main Nikla Gaddi Leke", artist: "Udit Narayan", year: 2001, videoId: "Q7ROtumJoKM", artwork: "/images/railway.jpg" },
      { id: 446, title: "Udd Ja Kaale Kaava", artist: "Udit Narayan, Alka Yagnik", year: 2001, videoId: "wseBkbzhauU", artwork: "/images/railway.jpg" },
      { id: 447, title: "Musafir Jaane Wale", artist: "Udit Narayan, Preeti Uttam", year: 2001, videoId: "I2nQfiux2sk", artwork: "/images/railway.jpg" },
      { id: 448, title: "Humko Humise Chura Lo", artist: "Lata Mangeshkar, Udit Narayan", year: 2000, videoId: "zWPsjhBaRb0", artwork: "/images/railway.jpg" },
      { id: 449, title: "Tum Se Hi", artist: "Mohit Chauhan", year: 2007, videoId: "mt9xg0mmt28", artwork: "/images/railway.jpg" },
      { id: 450, title: "Aaoge Jab Tum", artist: "Ustad Rashid Khan", year: 2007, videoId: "WPwTPhFMm3k", artwork: "/images/railway.jpg" },
      { id: 451, title: "Yeh Ishq Hai", artist: "Shreya Ghoshal", year: 2007, videoId: "dXpG0kavjUo", artwork: "/images/railway.jpg" },
      { id: 452, title: "Maahi Ve", artist: "Sadhana Sargam, Sonu Nigam", year: 2003, videoId: "1BWdglekty0", artwork: "/images/railway.jpg" },
      { id: 453, title: "Khaabon Ke Parinday", artist: "Mohit Chauhan, Alyssa Mendonsa", year: 2011, videoId: "R0XjwtP_iTY", artwork: "/images/railway.jpg" },
      { id: 454, title: "Der Lagi Lekin", artist: "Shankar Mahadevan", year: 2011, videoId: "b5pxCwiLl5w", artwork: "/images/railway.jpg" },
      { id: 455, title: "Dil Dhadakne Do", artist: "Shankar Mahadevan, Suraj Jagan", year: 2011, videoId: "WuMWwPHTSoY", artwork: "/images/railway.jpg" },
      { id: 456, title: "Ik Junoon", artist: "Vishal Dadlani, Shankar Mahadevan", year: 2011, videoId: "5PbWtDGOL8A", artwork: "/images/railway.jpg" },
      { id: 457, title: "Kabira", artist: "Tochi Raina, Rekha Bhardwaj", year: 2013, videoId: "jHNNMj5bNQw", artwork: "/images/railway.jpg" },
      { id: 458, title: "Balam Pichkari", artist: "Vishal Dadlani, Shalmali Kholgade", year: 2013, videoId: "0WtRNGubWGA", artwork: "/images/railway.jpg" },
      { id: 459, title: "Subhanallah", artist: "Sreerama Chandra, Shilpa Rao", year: 2013, videoId: "QYO6AlxiRE4", artwork: "/images/railway.jpg" },
      { id: 460, title: "Jo Bhi Main", artist: "Mohit Chauhan", year: 2011, videoId: "_kOzFMR9Hys", artwork: "/images/railway.jpg" },
      { id: 461, title: "Kun Faya Kun", artist: "A.R. Rahman, Javed Ali, Mohit Chauhan", year: 2011, videoId: "T94PHkuydcw", artwork: "/images/railway.jpg" },
      { id: 462, title: "Nadaan Parindey", artist: "A.R. Rahman, Mohit Chauhan", year: 2011, videoId: "ttIKsnxPrMY", artwork: "/images/railway.jpg" },
      { id: 463, title: "Awarapan Banjarapan", artist: "M.M. Keeravani", year: 2003, videoId: "zHgnRLWe_GE", artwork: "/images/railway.jpg" },
      { id: 464, title: "Tanhayee", artist: "Sonu Nigam", year: 2001, videoId: "ZkwaiIGoyT4", artwork: "/images/railway.jpg" },
      { id: 465, title: "Jaane Kyun", artist: "Vishal Dadlani, Sunidhi Chauhan", year: 2001, videoId: "n0PoVxBMUyE", artwork: "/images/railway.jpg" },
      { id: 466, title: "Woh Din", artist: "Arijit Singh", year: 2019, videoId: "-z_UvHknyrc", artwork: "/images/railway.jpg" },
      { id: 467, title: "Journey Song", artist: "Anupam Roy, Shreya Ghoshal", year: 2015, videoId: "2__nNm0NK4A", artwork: "/images/railway.jpg" },
      { id: 468, title: "Hawaa Hawaa", artist: "Mohit Chauhan", year: 2011, videoId: "xQryki2ZhYA", artwork: "/images/railway.jpg" },
      { id: 469, title: "Kyun Main Jaagoon", artist: "Shafqat Amanat Ali", year: 2011, videoId: "lN1m7zLBbSU", artwork: "/images/railway.jpg" },
      { id: 470, title: "Yeh Hausla", artist: "Shafqat Amanat Ali", year: 2006, videoId: "JwB_nGx7uAs", artwork: "/images/railway.jpg" },
      { id: 471, title: "Rinkiya Ke Papa", artist: "Manoj Tiwari", year: 2000, videoId: "8jF5RmI2YNU", artwork: "/images/railway.jpg" },
      { id: 472, title: "Bagalwali Jaan Mareli", artist: "Manoj Tiwari", year: 2007, videoId: "cp0u9xHBZJ4", artwork: "/images/railway.jpg" },
      { id: 473, title: "Goriya Chand Ke Anjoriya", artist: "Manoj Tiwari", year: 2005, videoId: "VOtS75Xlfgg", artwork: "/images/railway.jpg" },
      { id: 474, title: "Pardesi Balam", artist: "Bhojpuri Classic", year: 2010, videoId: "cRNdBrqSuak", artwork: "/images/railway.jpg" },
      { id: 475, title: "Piya Pardesi", artist: "Bhojpuri Hit", year: 2012, videoId: "Ackl9qhE-LA", artwork: "/images/railway.jpg" },
      { id: 476, title: "Saiyan Hamar", artist: "Bhojpuri Hit", year: 2010, videoId: "m40yAS42WVw", artwork: "/images/railway.jpg" },
      { id: 477, title: "Goriya Chali Jaibu", artist: "Bhojpuri Hit", year: 2013, videoId: "EStG4Y7S_-E", artwork: "/images/railway.jpg" },
      { id: 478, title: "Piyawa Se Pahile Hamaar Rahlu", artist: "Ritesh Pandey", year: 2017, videoId: "vwMR0yf4q04", artwork: "/images/railway.jpg" },
      { id: 479, title: "Ae Raja Tani Ja Na Bahariya", artist: "Pawan Singh", year: 2018, videoId: "3hg5N5hG1Cc", artwork: "/images/railway.jpg" },
      { id: 480, title: "Tohar Kajra Lagal Naina Mein", artist: "Bhojpuri Hit", year: 2011, videoId: "q2VZJQCuXi0", artwork: "/images/railway.jpg" },
      { id: 481, title: "Lal Chunariya Wali", artist: "Bhojpuri Hit", year: 2016, videoId: "hH38X-nTNAg", artwork: "/images/railway.jpg" },
      { id: 482, title: "Kashi Hile Patna Hile", artist: "Manoj Tiwari", year: 2002, videoId: "orVDnK0MyMo", artwork: "/images/railway.jpg" },
      { id: 483, title: "Aara Hile Chapra Hile", artist: "Khesari Lal Yadav", year: 2019, videoId: "zQqJmpCJZtc", artwork: "/images/railway.jpg" },
      { id: 484, title: "Ganga Maiya Tohe Piyari Chadhaibo", artist: "Bhojpuri Classic", year: 1963, videoId: "CPOp1s5RTAg", artwork: "/images/railway.jpg" },
      { id: 485, title: "Kach Kach Baans Ke Bahangiya", artist: "Bhojpuri Folk", year: 2008, videoId: "OSQI61ilOsM", artwork: "/images/railway.jpg" },
      { id: 486, title: "Chhalakata Hamro Jawaniya", artist: "Pawan Singh", year: 2016, videoId: "c4JD7rEtIj8", artwork: "/images/railway.jpg" },
      { id: 487, title: "Sasura Bada Paisawala", artist: "Manoj Tiwari", year: 2004, videoId: "aAwBKdd-zFg", artwork: "/images/railway.jpg" },
      { id: 488, title: "Daroga Babu I Love You", artist: "Shreya Ghoshal", year: 2004, videoId: "juLFr5LRIus", artwork: "/images/railway.jpg" },
      { id: 489, title: "Lalki Odhaniya", artist: "Manoj Tiwari", year: 2004, videoId: "2Q5EQinkh1c", artwork: "/images/railway.jpg" },
      { id: 490, title: "Chat Deni Maar Deli", artist: "Manoj Tiwari", year: 2008, videoId: "8jF5RmI2YNU", artwork: "/images/railway.jpg" },
      { id: 491, title: "Damad Ji", artist: "Manoj Tiwari", year: 2005, videoId: "TldcOm2KbQc", artwork: "/images/railway.jpg" },
      { id: 492, title: "Odhaniya Wali Se", artist: "Manoj Tiwari", year: 2006, videoId: "fedVbU26Gv0", artwork: "/images/railway.jpg" },
      { id: 493, title: "Saiyan Driver", artist: "Bhojpuri Hit", year: 2015, videoId: "8QxOat8s8Oo", artwork: "/images/railway.jpg" },
      { id: 494, title: "Raja Ho Raja", artist: "Bhojpuri Hit", year: 2014, videoId: "tnb7hSON80o", artwork: "/images/railway.jpg" },
      { id: 495, title: "Bhojpuriya Raja", artist: "Pawan Singh", year: 2016, videoId: "FF-_QBizdZQ", artwork: "/images/railway.jpg" },
      { id: 496, title: "Tohar Dupatta", artist: "Bhojpuri Hit", year: 2019, videoId: "8E7IsAvcQ6U", artwork: "/images/railway.jpg" },
      { id: 497, title: "Kareja Mein Samail Badu Ho", artist: "Pawan Singh", year: 2015, videoId: "PJx-Agxq2NM", artwork: "/images/railway.jpg" },
      { id: 498, title: "Ae Ho More Raja", artist: "Bhojpuri Hit", year: 2016, videoId: "cjaXzoCYnho", artwork: "/images/railway.jpg" },
      { id: 499, title: "Dilwa Mangele Gamcha Bichayike", artist: "Kalpana Patowary", year: 2010, videoId: "NNublffAZWc", artwork: "/images/railway.jpg" },
      { id: 500, title: "Lollypop Lagelu", artist: "Pawan Singh", year: 2008, videoId: "Gr8G_ldltDE", artwork: "/images/railway.jpg" }
    ]
  },
  {
    id: "mohalle-ki-shaam",
    title: 'Mohalle Ki Shaam',
    hindi: 'मोहल्ले की शाम',
    description: 'Cricket, doston ki awaaz aur galiyan',
    icon: '🏏',
    tint: 'violet',
    image: '/images/mohalla.jpg',
    ambienceAudio: '',
    playlist: [      { id: 501, title: "Ek Sanam Chahiye Aashiqui Ke Liye", artist: "Kumar Sanu", year: 1990, videoId: "yXbSZFNBvvE", artwork: "/images/mohalla.jpg" },
      { id: 502, title: "Ab Tere Bin Jee Lenge Hum", artist: "Kumar Sanu", year: 1990, videoId: "rTatsmUgmiA", artwork: "/images/mohalla.jpg" },
      { id: 503, title: "Nazar Ke Saamne", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "uNt18l9UfjE", artwork: "/images/mohalla.jpg" },
      { id: 504, title: "Ab Tere Bin", artist: "Kumar Sanu", year: 1990, videoId: "rTatsmUgmiA", artwork: "/images/mohalla.jpg" },
      { id: 505, title: "Jaane Jigar Jaaneman", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "waWcT-GD-yo", artwork: "/images/mohalla.jpg" },
      { id: 506, title: "Mera Dil Tera Hone Laga", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "rTuxUAuJRyY", artwork: "/images/mohalla.jpg" },
      { id: 507, title: "Akele Hain To Kya Gham Hai", artist: "Udit Narayan, Alka Yagnik", year: 1988, videoId: "As9DnNT3XZA", artwork: "/images/mohalla.jpg" },
      { id: 508, title: "Gazab Ka Hai Din", artist: "Udit Narayan, Alka Yagnik", year: 1988, videoId: "HgYiNVNsHwE", artwork: "/images/mohalla.jpg" },
      { id: 509, title: "Papa Kehte Hain", artist: "Udit Narayan", year: 1988, videoId: "FEvBiayarlc", artwork: "/images/mohalla.jpg" },
      { id: 510, title: "Ae Mere Humsafar", artist: "Vinod Rathod, Alka Yagnik", year: 1993, videoId: "UCsW7nea7sI", artwork: "/images/mohalla.jpg" },
      { id: 511, title: "Kitaben Bahut Si", artist: "Vinod Rathod, Asha Bhosle", year: 1993, videoId: "708MrJ6ZJsI", artwork: "/images/mohalla.jpg" },
      { id: 512, title: "Chhupana Bhi Nahin Aata", artist: "Vinod Rathod", year: 1993, videoId: "OsBqRHx2JAA", artwork: "/images/mohalla.jpg" },
      { id: 513, title: "Jaadu Teri Nazar", artist: "Udit Narayan", year: 1993, videoId: "n_oP9Onj0r0", artwork: "/images/mohalla.jpg" },
      { id: 514, title: "Tu Mere Saamne", artist: "Udit Narayan, Lata Mangeshkar", year: 1993, videoId: "0-7RHSbyZGw", artwork: "/images/mohalla.jpg" },
      { id: 515, title: "Likha Hai Yeh", artist: "Hariharan, Lata Mangeshkar", year: 1993, videoId: "tfSqvusJiFI", artwork: "/images/mohalla.jpg" },
      { id: 516, title: "Meri Mehbooba", artist: "Kumar Sanu, Alka Yagnik", year: 1997, videoId: "k2CuG5E4OAo", artwork: "/images/mohalla.jpg" },
      { id: 517, title: "Kisi Roz Tumse Mulaqat Hogi", artist: "Kumar Sanu, Alka Yagnik", year: 1997, videoId: "wOEJ-m9vgIA", artwork: "/images/mohalla.jpg" },
      { id: 518, title: "Neend Churaayi Meri", artist: "Kumar Sanu, Udit Narayan, Alka Yagnik, Kavita Krishnamurthy", year: 1997, videoId: "KYUcnSOwjxE", artwork: "/images/mohalla.jpg" },
      { id: 519, title: "Humko Sirf Tumse Pyaar Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1995, videoId: "t8aOUxUpoeI", artwork: "/images/mohalla.jpg" },
      { id: 520, title: "Tumhein Apna Banane Ki Kasam", artist: "Kumar Sanu, Anuradha Paudwal", year: 1991, videoId: "-aMgmlXHoT4", artwork: "/images/mohalla.jpg" },
      { id: 521, title: "Tumhein Apna Banane Ki Kasam Khai Hai", artist: "Kumar Sanu, Anuradha Paudwal", year: 1991, videoId: "-aMgmlXHoT4", artwork: "/images/mohalla.jpg" },
      { id: 522, title: "Tum Dil Ki Dhadkan Mein", artist: "Abhijeet, Alka Yagnik", year: 2000, videoId: "3Z_x7vBqr6E", artwork: "/images/mohalla.jpg" },
      { id: 523, title: "Dil Ne Yeh Kaha Hai Dil Se", artist: "Udit Narayan, Alka Yagnik, Kumar Sanu", year: 2000, videoId: "4msl5o59p8w", artwork: "/images/mohalla.jpg" },
      { id: 524, title: "Dulhe Ka Sehra", artist: "Nusrat Fateh Ali Khan", year: 2000, videoId: "iZAv9zDeFSc", artwork: "/images/mohalla.jpg" },
      { id: 525, title: "Aap Ki Kashish", artist: "Himesh Reshammiya, Ahir", year: 2005, videoId: "jx0qbW_YTCs", artwork: "/images/mohalla.jpg" },
      { id: 526, title: "Aashiq Banaya Aapne", artist: "Himesh Reshammiya, Shreya Ghoshal", year: 2005, videoId: "RlbGLrMuZ5I", artwork: "/images/mohalla.jpg" },
      { id: 527, title: "Woh Lamhe Woh Baatein", artist: "Atif Aslam", year: 2005, videoId: "t0gTfdNjPdw", artwork: "/images/mohalla.jpg" },
      { id: 528, title: "Agar Tum Mil Jao", artist: "Shreya Ghoshal", year: 2005, videoId: "2E2WA8_teMY", artwork: "/images/mohalla.jpg" },
      { id: 529, title: "Jaane Kyun Log Pyaar Karte Hain", artist: "Udit Narayan, Alka Yagnik", year: 2001, videoId: "zz5KauCbjPI", artwork: "/images/mohalla.jpg" },
      { id: 530, title: "Woh Ladki Hai Kahan", artist: "Shaan, Kavita Krishnamurthy", year: 2001, videoId: "IIg8H60bRJo", artwork: "/images/mohalla.jpg" },
      { id: 531, title: "Tanhayee", artist: "Sonu Nigam", year: 2001, videoId: "ZkwaiIGoyT4", artwork: "/images/mohalla.jpg" },
      { id: 532, title: "Kaisi Paheli Zindagani", artist: "Sunidhi Chauhan", year: 2005, videoId: "PTpiD4ezo6U", artwork: "/images/mohalla.jpg" },
      { id: 533, title: "Piyu Bole", artist: "Sonu Nigam, Shreya Ghoshal", year: 2005, videoId: "JZ0zD23Wq9E", artwork: "/images/mohalla.jpg" },
      { id: 534, title: "Kasto Mazza", artist: "Sonu Nigam, Shreya Ghoshal", year: 2005, videoId: "deTVgOf2cWs", artwork: "/images/mohalla.jpg" },
      { id: 535, title: "Aao Huzoor Tumko", artist: "Asha Bhosle", year: 1968, videoId: "PjXK0k3EQzg", artwork: "/images/mohalla.jpg" },
      { id: 536, title: "Kaho Na Kaho", artist: "Amir Jamal", year: 2004, videoId: "E-OM5ueIgDo", artwork: "/images/mohalla.jpg" },
      { id: 537, title: "Bheege Honth Tere", artist: "Kunal Ganjawala", year: 2004, videoId: "ojUTswFMjyM", artwork: "/images/mohalla.jpg" },
      { id: 538, title: "Jadu Hai Nasha Hai", artist: "Shreya Ghoshal", year: 2003, videoId: "gTSL0Rv0am4", artwork: "/images/mohalla.jpg" },
      { id: 539, title: "Awarapan Banjarapan", artist: "MM Keeravani", year: 2003, videoId: "zHgnRLWe_GE", artwork: "/images/mohalla.jpg" },
      { id: 540, title: "Zara Zara", artist: "Bombay Jayashri", year: 2001, videoId: "sjij_VKa2QQ", artwork: "/images/mohalla.jpg" },
      { id: 541, title: "Sach Keh Raha Hai Deewana", artist: "KK", year: 2001, videoId: "kp-Bqr1Gtyw", artwork: "/images/mohalla.jpg" },
      { id: 542, title: "Dil Ko Tumse Pyaar Hua", artist: "Roop Kumar Rathod", year: 2001, videoId: "XcMy3lyDaQg", artwork: "/images/mohalla.jpg" },
      { id: 543, title: "Humko Maaloom Hai", artist: "Sonu Nigam, Sadhana Sargam", year: 2006, videoId: "9jeFD4I6Zuk", artwork: "/images/mohalla.jpg" },
      { id: 544, title: "Ajnabi Shehar", artist: "Sonu Nigam", year: 2006, videoId: "J_0OkfLzzrQ", artwork: "/images/mohalla.jpg" },
      { id: 545, title: "Sau Dard", artist: "Sonu Nigam, Suzan", year: 2006, videoId: "xo8JU-Vc1C0", artwork: "/images/mohalla.jpg" },
      { id: 546, title: "Tere Bin", artist: "Atif Aslam", year: 2006, videoId: "GmbOGB91CYg", artwork: "/images/mohalla.jpg" },
      { id: 547, title: "Teri Yaadon Mein", artist: "KK, Shreya Ghoshal", year: 2006, videoId: "8UjuVi_-dvc", artwork: "/images/mohalla.jpg" },
      { id: 548, title: "Maine Dil Se Kaha", artist: "KK", year: 2003, videoId: "XvBzzvezdiU", artwork: "/images/mohalla.jpg" },
      { id: 549, title: "Toh Phir Aao", artist: "Mustafa Zahid", year: 2007, videoId: "n_VrRuNkbrE", artwork: "/images/mohalla.jpg" },
      { id: 550, title: "Mahiya", artist: "Annie Khalid", year: 2007, videoId: "vU3X1Bv18Ac", artwork: "/images/mohalla.jpg" },
      { id: 551, title: "Tujh Sang Lagi", artist: "Hit Song", year: 2007, videoId: "J_99AA-uCyI", artwork: "/images/mohalla.jpg" },
      { id: 552, title: "Kya Mujhe Pyaar Hai", artist: "KK", year: 2006, videoId: "lrAM_H7v8wM", artwork: "/images/mohalla.jpg" },
      { id: 553, title: "Tu Hi Meri Shab Hai", artist: "KK", year: 2006, videoId: "mWBvudKcByg", artwork: "/images/mohalla.jpg" },
      { id: 554, title: "Ya Ali", artist: "Zubeen Garg", year: 2006, videoId: "pmHnlBqjpm0", artwork: "/images/mohalla.jpg" },
      { id: 555, title: "Bheed Mein Tanhai Mein", artist: "Udit Narayan, Shreya Ghoshal", year: 2004, videoId: "Eu9LPo0gqeQ", artwork: "/images/mohalla.jpg" },
      { id: 556, title: "Mujhe Tumse Mohabbat Hai", artist: "Shreya Ghoshal, Shaan", year: 2004, videoId: "IWshQwwxceI", artwork: "/images/mohalla.jpg" },
      { id: 557, title: "Tere Bin", artist: "Rabbi Shergill", year: 2004, videoId: "PZvkvigWb9Y", artwork: "/images/mohalla.jpg" },
      { id: 558, title: "Aankhon Se Tune Kya Keh Diya", artist: "Kumar Sanu, Alka Yagnik", year: 1998, videoId: "RlSRxyxFwXI", artwork: "/images/mohalla.jpg" },
      { id: 559, title: "Aati Kya Khandala", artist: "Aamir Khan, Alka Yagnik", year: 1998, videoId: "EENnVk1_suc", artwork: "/images/mohalla.jpg" },
      { id: 560, title: "Chand Taare", artist: "Abhijeet", year: 1997, videoId: "N3QzaUwml5w", artwork: "/images/mohalla.jpg" },
      { id: 561, title: "Ek Din Aap Yun", artist: "Kumar Sanu, Alka Yagnik", year: 1997, videoId: "90Q5bMN6u2w", artwork: "/images/mohalla.jpg" },
      { id: 562, title: "Main Koi Aisa Geet Gaoon", artist: "Abhijeet, Alka Yagnik", year: 1997, videoId: "vzlXfZlH5dk", artwork: "/images/mohalla.jpg" },
      { id: 563, title: "Suniye To", artist: "Abhijeet", year: 1997, videoId: "RLFfZJV_gZU", artwork: "/images/mohalla.jpg" },
      { id: 564, title: "Mere Mehboob Mere Sanam", artist: "Udit Narayan, Alka Yagnik", year: 1998, videoId: "08rijnYeSIw", artwork: "/images/mohalla.jpg" },
      { id: 565, title: "Wah Ji Wah", artist: "Kumar Sanu", year: 1998, videoId: "X0h5hrRauog", artwork: "/images/mohalla.jpg" },
      { id: 566, title: "Kuch Kuch Hota Hai", artist: "Udit Narayan, Alka Yagnik", year: 1998, videoId: "bKZTnnFU9HA", artwork: "/images/mohalla.jpg" },
      { id: 567, title: "Koi Mil Gaya", artist: "Udit Narayan, Alka Yagnik, Kavita Krishnamurthy", year: 1998, videoId: "gmXlGQAg400", artwork: "/images/mohalla.jpg" },
      { id: 568, title: "Ladki Badi Anjaani Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1998, videoId: "oJcE_QPFAng", artwork: "/images/mohalla.jpg" },
      { id: 569, title: "Saajanji Ghar Aaye", artist: "Kumar Sanu, Alka Yagnik, Kavita Krishnamurthy", year: 1998, videoId: "8XtXLVylOoU", artwork: "/images/mohalla.jpg" },
      { id: 570, title: "Kavna Des Se Aail Badu", artist: "Bhojpuri Hit", year: 2012, videoId: "UKWir-2XAqE", artwork: "/images/mohalla.jpg" },
      { id: 571, title: "Hamra Lehnga Mein Meeter", artist: "Bhojpuri Hit", year: 2015, videoId: "GyNUg9AXPI4", artwork: "/images/mohalla.jpg" },
      { id: 572, title: "Balam Pardesiya", artist: "Bhojpuri Classic", year: 2008, videoId: "iFpBaYtFFM8", artwork: "/images/mohalla.jpg" },
      { id: 573, title: "Kaanch Hi Baans Ke Bahangiya", artist: "Bhojpuri Folk", year: 2008, videoId: "OSQI61ilOsM", artwork: "/images/mohalla.jpg" },
      { id: 574, title: "Ugi He Suruj Dev", artist: "Chhath Geet", year: 2005, videoId: "eNevbfmhn2o", artwork: "/images/mohalla.jpg" },
      { id: 575, title: "Pahile Pahile Pyar Ke", artist: "Bhojpuri Hit", year: 2014, videoId: "d5RkBumA3q0", artwork: "/images/mohalla.jpg" },
      { id: 576, title: "Kaise Bhulaib Tohra Ke", artist: "Bhojpuri Hit", year: 2016, videoId: "z50xNqpwbvo", artwork: "/images/mohalla.jpg" },
      { id: 577, title: "Tohra Se Pyar Ba", artist: "Bhojpuri Hit", year: 2017, videoId: "kdCKRgPYmTw", artwork: "/images/mohalla.jpg" },
      { id: 578, title: "Tohar Yaad Satave", artist: "Bhojpuri Hit", year: 2015, videoId: "hg4KHYShi-w", artwork: "/images/mohalla.jpg" },
      { id: 579, title: "Sajna O Sajna", artist: "Bhojpuri Hit", year: 2013, videoId: "JRKk7gxcpMc", artwork: "/images/mohalla.jpg" },
      { id: 580, title: "Ae Saiyan Hamaar", artist: "Bhojpuri Hit", year: 2010, videoId: "c-AyVdrrSE0", artwork: "/images/mohalla.jpg" },
      { id: 581, title: "Piyawa Ke Des", artist: "Bhojpuri Hit", year: 2012, videoId: "5CmWRy4N1bg", artwork: "/images/mohalla.jpg" },
      { id: 582, title: "Balamua Ho Tohar", artist: "Bhojpuri Hit", year: 2011, videoId: "IkEclxxwNdc", artwork: "/images/mohalla.jpg" },
      { id: 583, title: "Gori Ho Gori", artist: "Bhojpuri Hit", year: 2014, videoId: "LsxTWENKmL4", artwork: "/images/mohalla.jpg" },
      { id: 584, title: "Chadhal Jawani", artist: "Bhojpuri Hit", year: 2018, videoId: "CFiIg37Ud4s", artwork: "/images/mohalla.jpg" },
      { id: 585, title: "Kaise Kati Dinwa", artist: "Bhojpuri Hit", year: 2013, videoId: "fFKQK8h7y_k", artwork: "/images/mohalla.jpg" },
      { id: 586, title: "Aaja Ae Sanam", artist: "Bhojpuri Hit", year: 2016, videoId: "E4HsFJe2KLY", artwork: "/images/mohalla.jpg" },
      { id: 587, title: "Tohra Bin Jee Na Paib", artist: "Bhojpuri Hit", year: 2015, videoId: "HWpWicgJ2pM", artwork: "/images/mohalla.jpg" },
      { id: 588, title: "Pyar Ke Rog Lagal", artist: "Bhojpuri Hit", year: 2014, videoId: "E81EwWvn-aI", artwork: "/images/mohalla.jpg" },
      { id: 589, title: "Naina Lad Jaihen", artist: "Bhojpuri Hit", year: 2017, videoId: "_7Gcg5DmMGo", artwork: "/images/mohalla.jpg" },
      { id: 590, title: "Saj Ke Sawar Ke", artist: "Khesari Lal Yadav", year: 2018, videoId: "y3Jc2kxaqdw", artwork: "/images/mohalla.jpg" },
      { id: 591, title: "Balam Ji I Love You", artist: "Khesari Lal Yadav", year: 2018, videoId: "dGi_-PhjRqY", artwork: "/images/mohalla.jpg" },
      { id: 592, title: "Jaan Lebu Ka Ho", artist: "Pawan Singh", year: 2019, videoId: "cMfDLdHFr8I", artwork: "/images/mohalla.jpg" },
      { id: 593, title: "Pyar Mein Tohra", artist: "Bhojpuri Hit", year: 2017, videoId: "b4FwkYaeYvI", artwork: "/images/mohalla.jpg" },
      { id: 594, title: "Kaise Kati Ratiya", artist: "Bhojpuri Hit", year: 2015, videoId: "L8I0rN-NwdM", artwork: "/images/mohalla.jpg" },
      { id: 595, title: "Goriya Ke Muski", artist: "Bhojpuri Hit", year: 2016, videoId: "7mQHPuEKzZE", artwork: "/images/mohalla.jpg" },
      { id: 596, title: "Tohar Muski", artist: "Bhojpuri Hit", year: 2018, videoId: "7mQHPuEKzZE", artwork: "/images/mohalla.jpg" },
      { id: 597, title: "Jab Se Bani Tu Dulhan", artist: "Bhojpuri Hit", year: 2015, videoId: "tvjaJ5sn3N8", artwork: "/images/mohalla.jpg" },
      { id: 598, title: "Sasura Mein Jaake", artist: "Bhojpuri Hit", year: 2014, videoId: "wEoY4Sis0GE", artwork: "/images/mohalla.jpg" },
      { id: 599, title: "Hamra Ke Bhula Gailu", artist: "Bhojpuri Hit", year: 2016, videoId: "HjzeQrO-HOE", artwork: "/images/mohalla.jpg" }
    ]
  },
  {
    id: "purana-radio",
    title: 'Purana Radio',
    hindi: 'पुराना रेडियो',
    description: 'Aawaaz jo ghar ko ghar banati thi',
    icon: '📻',
    tint: 'blue',
    image: '/images/radio.jpg',
    ambienceAudio: '',
    playlist: [      { id: 601, title: "Tumhein Apna Banane Ki Kasam", artist: "Kumar Sanu, Anuradha Paudwal", year: 1991, videoId: "-aMgmlXHoT4", artwork: "/images/radio.jpg" },
      { id: 602, title: "Tu Pyar Hai Kisi Aur Ka", artist: "Kumar Sanu, Anuradha Paudwal", year: 1991, videoId: "47DstHmE-bE", artwork: "/images/radio.jpg" },
      { id: 603, title: "Saathiya Tune Kya Kiya", artist: "SP Balasubrahmanyam, Chithra", year: 1991, videoId: "RpEywqAuH4U", artwork: "/images/radio.jpg" },
      { id: 604, title: "Tu Shaayar Hai Main Teri Shaayari", artist: "Alka Yagnik", year: 1991, videoId: "ioWh9vMixyw", artwork: "/images/radio.jpg" },
      { id: 605, title: "Bahut Pyar Karte Hain", artist: "SP Balasubrahmanyam, Anuradha Paudwal", year: 1991, videoId: "2l5gDrfBQ_A", artwork: "/images/radio.jpg" },
      { id: 606, title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1991, videoId: "npDZyWtu9_A", artwork: "/images/radio.jpg" },
      { id: 607, title: "Jeeye To Jeeye Kaise", artist: "Kumar Sanu, SP Balasubrahmanyam", year: 1991, videoId: "XOxz0Hr3Hzo", artwork: "/images/radio.jpg" },
      { id: 608, title: "Dheere Dheere Se Meri Zindagi Mein Aana", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "KeyfUuXPOcY", artwork: "/images/radio.jpg" },
      { id: 609, title: "Nazar Ke Saamne", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "uNt18l9UfjE", artwork: "/images/radio.jpg" },
      { id: 610, title: "Ek Sanam Chahiye Aashiqui Ke Liye", artist: "Kumar Sanu", year: 1990, videoId: "yXbSZFNBvvE", artwork: "/images/radio.jpg" },
      { id: 611, title: "Ab Tere Bin Jee Lenge Hum", artist: "Kumar Sanu", year: 1990, videoId: "rTatsmUgmiA", artwork: "/images/radio.jpg" },
      { id: 612, title: "Jaane Jigar Jaaneman", artist: "Kumar Sanu, Anuradha Paudwal", year: 1990, videoId: "waWcT-GD-yo", artwork: "/images/radio.jpg" },
      { id: 613, title: "Akele Hain To Kya Gham Hai", artist: "Udit Narayan, Alka Yagnik", year: 1988, videoId: "As9DnNT3XZA", artwork: "/images/radio.jpg" },
      { id: 614, title: "Gazab Ka Hai Din", artist: "Udit Narayan, Alka Yagnik", year: 1988, videoId: "HgYiNVNsHwE", artwork: "/images/radio.jpg" },
      { id: 615, title: "Papa Kehte Hain", artist: "Udit Narayan", year: 1988, videoId: "FEvBiayarlc", artwork: "/images/radio.jpg" },
      { id: 616, title: "Ae Mere Humsafar", artist: "Vinod Rathod, Alka Yagnik", year: 1993, videoId: "UCsW7nea7sI", artwork: "/images/radio.jpg" },
      { id: 617, title: "Kitaben Bahut Si", artist: "Vinod Rathod, Asha Bhosle", year: 1993, videoId: "708MrJ6ZJsI", artwork: "/images/radio.jpg" },
      { id: 618, title: "Chhupana Bhi Nahin Aata", artist: "Vinod Rathod", year: 1993, videoId: "OsBqRHx2JAA", artwork: "/images/radio.jpg" },
      { id: 619, title: "Jaadu Teri Nazar", artist: "Udit Narayan", year: 1993, videoId: "n_oP9Onj0r0", artwork: "/images/radio.jpg" },
      { id: 620, title: "Tu Mere Saamne", artist: "Udit Narayan, Lata Mangeshkar", year: 1993, videoId: "0-7RHSbyZGw", artwork: "/images/radio.jpg" },
      { id: 621, title: "Meri Mehbooba", artist: "Kumar Sanu, Alka Yagnik", year: 1997, videoId: "k2CuG5E4OAo", artwork: "/images/radio.jpg" },
      { id: 622, title: "Kisi Roz Tumse Mulaqat Hogi", artist: "Kumar Sanu, Alka Yagnik", year: 1997, videoId: "wOEJ-m9vgIA", artwork: "/images/radio.jpg" },
      { id: 623, title: "Humko Sirf Tumse Pyaar Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1995, videoId: "t8aOUxUpoeI", artwork: "/images/radio.jpg" },
      { id: 624, title: "Humko Humise Chura Lo", artist: "Lata Mangeshkar, Udit Narayan", year: 2000, videoId: "zWPsjhBaRb0", artwork: "/images/radio.jpg" },
      { id: 625, title: "Taal Se Taal Mila", artist: "Alka Yagnik, Udit Narayan", year: 1999, videoId: "OinGHNpnGtc", artwork: "/images/radio.jpg" },
      { id: 626, title: "Ishq Bina", artist: "Sujata, Sonu Nigam, A.R. Rahman", year: 1999, videoId: "QGPPGAj_1Lc", artwork: "/images/radio.jpg" },
      { id: 627, title: "Kariye Na", artist: "Sukhwinder Singh, Alka Yagnik", year: 1999, videoId: "qkBQ5GF5uvg", artwork: "/images/radio.jpg" },
      { id: 628, title: "Choli Ke Peeche Kya Hai", artist: "Ila Arun, Alka Yagnik", year: 1993, videoId: "OX1iSdqJ6Uo", artwork: "/images/radio.jpg" },
      { id: 629, title: "Nayak Nahin Khalnayak Hoon Main", artist: "Kavita Krishnamurthy, Vinod Rathod", year: 1993, videoId: "Jjibd7HZmNk", artwork: "/images/radio.jpg" },
      { id: 630, title: "Chandni O Meri Chandni", artist: "Sridevi, Jolly Mukherjee", year: 1989, videoId: "dRvvrAmcCJw", artwork: "/images/radio.jpg" },
      { id: 631, title: "Sochenge Tumhe Pyar", artist: "Kumar Sanu", year: 1992, videoId: "WkwDLxj5Wyo", artwork: "/images/radio.jpg" },
      { id: 632, title: "Aisi Deewangi", artist: "Alka Yagnik, Vinod Rathod", year: 1992, videoId: "iRycjp7XVMg", artwork: "/images/radio.jpg" },
      { id: 633, title: "Kisi Se Tum Pyar Karo", artist: "Kumar Sanu, Alka Yagnik", year: 2003, videoId: "JOt45suga2s", artwork: "/images/radio.jpg" },
      { id: 634, title: "Kitna Haseen Chehra", artist: "Kumar Sanu", year: 1994, videoId: "NzZxyWr9OA4", artwork: "/images/radio.jpg" },
      { id: 635, title: "Mausam Ki Tarah Tum Bhi", artist: "Manhar Udhas, Alka Yagnik", year: 1999, videoId: "1af5Ief2840", artwork: "/images/radio.jpg" },
      { id: 636, title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", year: 1995, videoId: "s1LozokQjIg", artwork: "/images/radio.jpg" },
      { id: 637, title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", year: 1995, videoId: "jBpRItrod-Q", artwork: "/images/radio.jpg" },
      { id: 638, title: "Humein Jab Se Mohabbat", artist: "Sonu Nigam, Alka Yagnik", year: 1997, videoId: "jor_SaUzuVI", artwork: "/images/radio.jpg" },
      { id: 639, title: "To Chalun", artist: "Roop Kumar Rathod", year: 1997, videoId: "6wbCAsB4UoY", artwork: "/images/radio.jpg" },
      { id: 640, title: "Sandese Aate Hain", artist: "Roop Kumar Rathod, Sonu Nigam", year: 1997, videoId: "yccGxvIydKg", artwork: "/images/radio.jpg" },
      { id: 641, title: "Ke Ghar Kab Aaoge", artist: "Sonu Nigam, Roop Kumar Rathod", year: 1997, videoId: "oodOj8jx8ds", artwork: "/images/radio.jpg" },
      { id: 642, title: "Pyar Ko Ho Jaane Do", artist: "Kumar Sanu, Lata Mangeshkar", year: 1998, videoId: "ZMiYNQ7hH0g", artwork: "/images/radio.jpg" },
      { id: 643, title: "Aankhon Se Tune Kya Keh Diya", artist: "Kumar Sanu, Alka Yagnik", year: 1998, videoId: "RlSRxyxFwXI", artwork: "/images/radio.jpg" },
      { id: 644, title: "Aati Kya Khandala", artist: "Aamir Khan, Alka Yagnik", year: 1998, videoId: "EENnVk1_suc", artwork: "/images/radio.jpg" },
      { id: 645, title: "Chand Taare", artist: "Abhijeet", year: 1997, videoId: "N3QzaUwml5w", artwork: "/images/radio.jpg" },
      { id: 646, title: "Ek Din Aap Yun", artist: "Kumar Sanu, Alka Yagnik", year: 1997, videoId: "90Q5bMN6u2w", artwork: "/images/radio.jpg" },
      { id: 647, title: "Main Koi Aisa Geet Gaoon", artist: "Abhijeet, Alka Yagnik", year: 1997, videoId: "vzlXfZlH5dk", artwork: "/images/radio.jpg" },
      { id: 648, title: "Mere Mehboob Mere Sanam", artist: "Udit Narayan, Alka Yagnik", year: 1998, videoId: "08rijnYeSIw", artwork: "/images/radio.jpg" },
      { id: 649, title: "Kuch Kuch Hota Hai", artist: "Udit Narayan, Alka Yagnik", year: 1998, videoId: "bKZTnnFU9HA", artwork: "/images/radio.jpg" },
      { id: 650, title: "Koi Mil Gaya", artist: "Udit Narayan, Alka Yagnik, Kavita Krishnamurthy", year: 1998, videoId: "gmXlGQAg400", artwork: "/images/radio.jpg" },
      { id: 651, title: "Ladki Badi Anjaani Hai", artist: "Kumar Sanu, Alka Yagnik", year: 1998, videoId: "oJcE_QPFAng", artwork: "/images/radio.jpg" },
      { id: 652, title: "Saajanji Ghar Aaye", artist: "Kumar Sanu, Alka Yagnik, Kavita Krishnamurthy", year: 1998, videoId: "8XtXLVylOoU", artwork: "/images/radio.jpg" },
      { id: 653, title: "Dil Ne Yeh Kaha Hai Dil Se", artist: "Udit Narayan, Alka Yagnik, Kumar Sanu", year: 2000, videoId: "4msl5o59p8w", artwork: "/images/radio.jpg" },
      { id: 654, title: "Tum Dil Ki Dhadkan Mein", artist: "Abhijeet, Alka Yagnik", year: 2000, videoId: "3Z_x7vBqr6E", artwork: "/images/radio.jpg" },
      { id: 655, title: "Dulhe Ka Sehra", artist: "Nusrat Fateh Ali Khan", year: 2000, videoId: "7LjT1TwzOd0", artwork: "/images/radio.jpg" },
      { id: 656, title: "Tumse Milna", artist: "Udit Narayan, Alka Yagnik", year: 2003, videoId: "3Y9zjI9oWaY", artwork: "/images/radio.jpg" },
      { id: 657, title: "Lagan Lagi", artist: "Sukhwinder Singh", year: 2003, videoId: "Ia1vUWaoqzE", artwork: "/images/radio.jpg" },
      { id: 658, title: "Odhli Chunariya", artist: "Kumar Sanu, Alka Yagnik", year: 1998, videoId: "qEa4aGq0nuU", artwork: "/images/radio.jpg" },
      { id: 659, title: "Aap Ki Kashish", artist: "Himesh Reshammiya", year: 2005, videoId: "jx0qbW_YTCs", artwork: "/images/radio.jpg" },
      { id: 660, title: "Aashiq Banaya Aapne", artist: "Himesh Reshammiya, Shreya Ghoshal", year: 2005, videoId: "RlbGLrMuZ5I", artwork: "/images/radio.jpg" },
      { id: 661, title: "Woh Lamhe Woh Baatein", artist: "Atif Aslam", year: 2005, videoId: "t0gTfdNjPdw", artwork: "/images/radio.jpg" },
      { id: 662, title: "Agar Tum Mil Jao", artist: "Shreya Ghoshal", year: 2005, videoId: "2E2WA8_teMY", artwork: "/images/radio.jpg" },
      { id: 663, title: "Kya Mujhe Pyaar Hai", artist: "KK", year: 2006, videoId: "lrAM_H7v8wM", artwork: "/images/radio.jpg" },
      { id: 664, title: "Tu Hi Meri Shab Hai", artist: "KK", year: 2006, videoId: "mWBvudKcByg", artwork: "/images/radio.jpg" },
      { id: 665, title: "Ya Ali", artist: "Zubeen Garg", year: 2006, videoId: "pmHnlBqjpm0", artwork: "/images/radio.jpg" },
      { id: 666, title: "Maine Dil Se Kaha", artist: "KK", year: 2003, videoId: "XvBzzvezdiU", artwork: "/images/radio.jpg" },
      { id: 667, title: "Tere Bin", artist: "Atif Aslam", year: 2006, videoId: "GmbOGB91CYg", artwork: "/images/radio.jpg" },
      { id: 668, title: "Kaho Na Kaho", artist: "Amir Jamal", year: 2004, videoId: "E-OM5ueIgDo", artwork: "/images/radio.jpg" },
      { id: 669, title: "Bheege Honth Tere", artist: "Kunal Ganjawala", year: 2004, videoId: "ojUTswFMjyM", artwork: "/images/radio.jpg" },
      { id: 670, title: "Jadu Hai Nasha Hai", artist: "Shreya Ghoshal", year: 2003, videoId: "gTSL0Rv0am4", artwork: "/images/radio.jpg" },
      { id: 671, title: "Sach Keh Raha Hai Deewana", artist: "KK", year: 2001, videoId: "kp-Bqr1Gtyw", artwork: "/images/radio.jpg" },
      { id: 672, title: "Dil Ko Tumse Pyaar Hua", artist: "Roop Kumar Rathod", year: 2001, videoId: "XcMy3lyDaQg", artwork: "/images/radio.jpg" },
      { id: 673, title: "Zara Zara", artist: "Bombay Jayashri", year: 2001, videoId: "sjij_VKa2QQ", artwork: "/images/radio.jpg" },
      { id: 674, title: "Ajnabi Shehar", artist: "Sonu Nigam", year: 2006, videoId: "J_0OkfLzzrQ", artwork: "/images/radio.jpg" },
      { id: 675, title: "Sau Dard", artist: "Sonu Nigam, Suzan", year: 2006, videoId: "xo8JU-Vc1C0", artwork: "/images/radio.jpg" },
      { id: 676, title: "Tere Bin", artist: "Rabbi Shergill", year: 2004, videoId: "PZvkvigWb9Y", artwork: "/images/radio.jpg" },
      { id: 677, title: "Mahiya", artist: "Annie Khalid", year: 2007, videoId: "vU3X1Bv18Ac", artwork: "/images/radio.jpg" },
      { id: 678, title: "Toh Phir Aao", artist: "Mustafa Zahid", year: 2007, videoId: "n_VrRuNkbrE", artwork: "/images/radio.jpg" },
      { id: 679, title: "Awarapan Banjarapan", artist: "MM Keeravani", year: 2003, videoId: "zHgnRLWe_GE", artwork: "/images/radio.jpg" },
      { id: 680, title: "Bheed Mein Tanhai Mein", artist: "Udit Narayan, Shreya Ghoshal", year: 2004, videoId: "Eu9LPo0gqeQ", artwork: "/images/radio.jpg" },
      { id: 681, title: "Balam Pardesiya", artist: "Bhojpuri Classic", year: 2008, videoId: "iFpBaYtFFM8", artwork: "/images/radio.jpg" },
      { id: 682, title: "Pahile Pahile Pyar Ke", artist: "Bhojpuri Hit", year: 2014, videoId: "d5RkBumA3q0", artwork: "/images/radio.jpg" },
      { id: 683, title: "Tohra Se Pyar Ba", artist: "Bhojpuri Hit", year: 2017, videoId: "sLljY7__bGo", artwork: "/images/radio.jpg" },
      { id: 684, title: "Kaise Bhulaib Tohra Ke", artist: "Bhojpuri Hit", year: 2016, videoId: "A1Fg1fP5QB4", artwork: "/images/radio.jpg" },
      { id: 685, title: "Tohar Yaad Satave", artist: "Bhojpuri Hit", year: 2015, videoId: "hg4KHYShi-w", artwork: "/images/radio.jpg" },
      { id: 686, title: "Ae Saiyan Hamaar", artist: "Bhojpuri Hit", year: 2010, videoId: "MOnyF57DyC0", artwork: "/images/radio.jpg" },
      { id: 687, title: "Piyawa Ke Des", artist: "Bhojpuri Hit", year: 2012, videoId: "vGoh_J5Fvak", artwork: "/images/radio.jpg" },
      { id: 688, title: "Balamua Ho Tohar", artist: "Bhojpuri Hit", year: 2011, videoId: "IkEclxxwNdc", artwork: "/images/radio.jpg" },
      { id: 689, title: "Gori Ho Gori", artist: "Bhojpuri Hit", year: 2014, videoId: "h9-siM7jyZI", artwork: "/images/radio.jpg" },
      { id: 690, title: "Kaise Kati Dinwa", artist: "Bhojpuri Hit", year: 2013, videoId: "fFKQK8h7y_k", artwork: "/images/radio.jpg" },
      { id: 691, title: "Tohra Bin Jee Na Paib", artist: "Bhojpuri Hit", year: 2015, videoId: "HWpWicgJ2pM", artwork: "/images/radio.jpg" },
      { id: 692, title: "Pyar Ke Rog Lagal", artist: "Bhojpuri Hit", year: 2014, videoId: "b3u8bWUHBa0", artwork: "/images/radio.jpg" },
      { id: 693, title: "Naina Lad Jaihen", artist: "Bhojpuri Hit", year: 2017, videoId: "_7Gcg5DmMGo", artwork: "/images/radio.jpg" },
      { id: 694, title: "Saj Ke Sawar Ke", artist: "Khesari Lal Yadav", year: 2018, videoId: "y3Jc2kxaqdw", artwork: "/images/radio.jpg" },
      { id: 695, title: "Balam Ji I Love You", artist: "Khesari Lal Yadav", year: 2018, videoId: "dGi_-PhjRqY", artwork: "/images/radio.jpg" },
      { id: 696, title: "Jaan Lebu Ka Ho", artist: "Pawan Singh", year: 2019, videoId: "3kqq4Tt5Cco", artwork: "/images/radio.jpg" },
      { id: 697, title: "Pyar Mein Tohra", artist: "Bhojpuri Hit", year: 2017, videoId: "opsKeI9EGqs", artwork: "/images/radio.jpg" },
      { id: 698, title: "Kaise Kati Ratiya", artist: "Bhojpuri Hit", year: 2015, videoId: "L8I0rN-NwdM", artwork: "/images/radio.jpg" },
      { id: 699, title: "Goriya Ke Muski", artist: "Bhojpuri Hit", year: 2016, videoId: "7mQHPuEKzZE", artwork: "/images/radio.jpg" },
      { id: 700, title: "Hamra Ke Bhula Gailu", artist: "Bhojpuri Hit", year: 2016, videoId: "w3KXLounzus", artwork: "/images/radio.jpg" }
    ]
  }
];
